// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NetworkAcsConfigs Network-wide config of acsd, the TR-069 ACS on the AGWs. An expired acs entitlement forces mode frozen whatever is set here.
//
// Example: {"mode":"active","periodic_inform_interval":300,"port":0}
//
// swagger:model network_acs_configs
type NetworkAcsConfigs struct {

	// active serves CPEs; frozen answers their Informs but sends them nothing (no tasks), so they keep their configuration.
	//
	// Enum: [active frozen]
	Mode *string `json:"mode,omitempty"`

	// PeriodicInformInterval pushed to CPEs, in seconds; 0 leaves the CPE value
	// Maximum: 86400
	// Minimum: 0
	PeriodicInformInterval *int32 `json:"periodic_inform_interval,omitempty"`

	// CWMP listener port on mtr0; 0 uses the port in acsd.yml
	// Maximum: 65535
	// Minimum: 0
	Port *int32 `json:"port,omitempty"`
}

// Validate validates this network acs configs
func (m *NetworkAcsConfigs) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePeriodicInformInterval(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePort(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var networkAcsConfigsTypeModePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["active","frozen"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		networkAcsConfigsTypeModePropEnum = append(networkAcsConfigsTypeModePropEnum, v)
	}
}

const (

	// NetworkAcsConfigsModeActive captures enum value "active"
	NetworkAcsConfigsModeActive string = "active"

	// NetworkAcsConfigsModeFrozen captures enum value "frozen"
	NetworkAcsConfigsModeFrozen string = "frozen"
)

// prop value enum
func (m *NetworkAcsConfigs) validateModeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, networkAcsConfigsTypeModePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *NetworkAcsConfigs) validateMode(formats strfmt.Registry) error {
	if swag.IsZero(m.Mode) { // not required
		return nil
	}

	// value enum
	if err := m.validateModeEnum("mode", "body", *m.Mode); err != nil {
		return err
	}

	return nil
}

func (m *NetworkAcsConfigs) validatePeriodicInformInterval(formats strfmt.Registry) error {
	if swag.IsZero(m.PeriodicInformInterval) { // not required
		return nil
	}

	if err := validate.MinimumInt("periodic_inform_interval", "body", int64(*m.PeriodicInformInterval), 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("periodic_inform_interval", "body", int64(*m.PeriodicInformInterval), 86400, false); err != nil {
		return err
	}

	return nil
}

func (m *NetworkAcsConfigs) validatePort(formats strfmt.Registry) error {
	if swag.IsZero(m.Port) { // not required
		return nil
	}

	if err := validate.MinimumInt("port", "body", int64(*m.Port), 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("port", "body", int64(*m.Port), 65535, false); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this network acs configs based on context it is used
func (m *NetworkAcsConfigs) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NetworkAcsConfigs) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NetworkAcsConfigs) UnmarshalBinary(b []byte) error {
	var res NetworkAcsConfigs
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
