// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// EntitlementState Effective state, computed by the server: active, grace (expired, still working), frozen (expired past the grace period) or disabled (switched off). Read-only.
//
// swagger:model entitlement_state
type EntitlementState string

func NewEntitlementState(value EntitlementState) *EntitlementState {
	return &value
}

// Pointer returns a pointer to a freshly-allocated EntitlementState.
func (m EntitlementState) Pointer() *EntitlementState {
	return &m
}

const (

	// EntitlementStateActive captures enum value "active"
	EntitlementStateActive EntitlementState = "active"

	// EntitlementStateGrace captures enum value "grace"
	EntitlementStateGrace EntitlementState = "grace"

	// EntitlementStateFrozen captures enum value "frozen"
	EntitlementStateFrozen EntitlementState = "frozen"

	// EntitlementStateDisabled captures enum value "disabled"
	EntitlementStateDisabled EntitlementState = "disabled"
)

// for schema
var entitlementStateEnum []interface{}

func init() {
	var res []EntitlementState
	if err := json.Unmarshal([]byte(`["active","grace","frozen","disabled"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		entitlementStateEnum = append(entitlementStateEnum, v)
	}
}

func (m EntitlementState) validateEntitlementStateEnum(path, location string, value EntitlementState) error {
	if err := validate.EnumCase(path, location, value, entitlementStateEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this entitlement state
func (m EntitlementState) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateEntitlementStateEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validate this entitlement state based on the context it is used
func (m EntitlementState) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := validate.ReadOnly(ctx, "", "body", EntitlementState(m)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
