// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Entitlement Permission of one tenant to use one licensed feature. Past not_after the feature keeps working for grace_days; after that it is frozen (REST read-only, gateway services frozen), never removed.
//
// swagger:model entitlement
type Entitlement struct {

	// False switches the feature off for the tenant
	// Required: true
	Enabled bool `json:"enabled"`

	// Feature ID, e.g. acs
	// Required: true
	// Pattern: ^[a-z][a-z0-9_]{0,63}$
	Feature string `json:"feature"`

	// Days past not_after during which nothing changes
	// Maximum: 3650
	// Minimum: 0
	GraceDays *int32 `json:"grace_days,omitempty"`

	// The license artefact this entitlement came from
	// Max Length: 255
	LicenseID string `json:"license_id,omitempty"`

	// Expiry; omitted means no expiry
	// Format: date-time
	NotAfter *strfmt.DateTime `json:"not_after,omitempty"`

	// Who set the entitlement
	// Enum: [manual license]
	Source *string `json:"source,omitempty"`

	// state
	State EntitlementState `json:"state,omitempty"`

	// Last change, set by the server
	// Read Only: true
	// Format: date-time
	UpdatedAt strfmt.DateTime `json:"updated_at,omitempty"`
}

// Validate validates this entitlement
func (m *Entitlement) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEnabled(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFeature(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGraceDays(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLicenseID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNotAfter(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSource(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateState(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Entitlement) validateEnabled(formats strfmt.Registry) error {

	if err := validate.Required("enabled", "body", bool(m.Enabled)); err != nil {
		return err
	}

	return nil
}

func (m *Entitlement) validateFeature(formats strfmt.Registry) error {

	if err := validate.RequiredString("feature", "body", m.Feature); err != nil {
		return err
	}

	if err := validate.Pattern("feature", "body", m.Feature, `^[a-z][a-z0-9_]{0,63}$`); err != nil {
		return err
	}

	return nil
}

func (m *Entitlement) validateGraceDays(formats strfmt.Registry) error {
	if swag.IsZero(m.GraceDays) { // not required
		return nil
	}

	if err := validate.MinimumInt("grace_days", "body", int64(*m.GraceDays), 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("grace_days", "body", int64(*m.GraceDays), 3650, false); err != nil {
		return err
	}

	return nil
}

func (m *Entitlement) validateLicenseID(formats strfmt.Registry) error {
	if swag.IsZero(m.LicenseID) { // not required
		return nil
	}

	if err := validate.MaxLength("license_id", "body", m.LicenseID, 255); err != nil {
		return err
	}

	return nil
}

func (m *Entitlement) validateNotAfter(formats strfmt.Registry) error {
	if swag.IsZero(m.NotAfter) { // not required
		return nil
	}

	if err := validate.FormatOf("not_after", "body", "date-time", m.NotAfter.String(), formats); err != nil {
		return err
	}

	return nil
}

var entitlementTypeSourcePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["manual","license"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		entitlementTypeSourcePropEnum = append(entitlementTypeSourcePropEnum, v)
	}
}

const (

	// EntitlementSourceManual captures enum value "manual"
	EntitlementSourceManual string = "manual"

	// EntitlementSourceLicense captures enum value "license"
	EntitlementSourceLicense string = "license"
)

// prop value enum
func (m *Entitlement) validateSourceEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, entitlementTypeSourcePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *Entitlement) validateSource(formats strfmt.Registry) error {
	if swag.IsZero(m.Source) { // not required
		return nil
	}

	// value enum
	if err := m.validateSourceEnum("source", "body", *m.Source); err != nil {
		return err
	}

	return nil
}

func (m *Entitlement) validateState(formats strfmt.Registry) error {
	if swag.IsZero(m.State) { // not required
		return nil
	}

	if err := m.State.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("state")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("state")
		}
		return err
	}

	return nil
}

func (m *Entitlement) validateUpdatedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.UpdatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("updated_at", "body", "date-time", m.UpdatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this entitlement based on the context it is used
func (m *Entitlement) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateState(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUpdatedAt(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Entitlement) contextValidateState(ctx context.Context, formats strfmt.Registry) error {

	if err := m.State.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("state")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("state")
		}
		return err
	}

	return nil
}

func (m *Entitlement) contextValidateUpdatedAt(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "updated_at", "body", strfmt.DateTime(m.UpdatedAt)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Entitlement) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Entitlement) UnmarshalBinary(b []byte) error {
	var res Entitlement
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
