// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NetworkEntitlements network entitlements
//
// swagger:model network_entitlements
type NetworkEntitlements struct {

	// Whether this Orc8r enforces entitlements. When false every feature behaves as entitled whatever the records say.
	//
	// Required: true
	Enforce bool `json:"enforce"`

	// entitlements
	// Required: true
	Entitlements []*Entitlement `json:"entitlements"`

	// network id
	// Required: true
	NetworkID string `json:"network_id"`

	// The tenant that owns the network; omitted when none does
	TenantID *int64 `json:"tenant_id,omitempty"`
}

// Validate validates this network entitlements
func (m *NetworkEntitlements) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEnforce(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEntitlements(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNetworkID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NetworkEntitlements) validateEnforce(formats strfmt.Registry) error {

	if err := validate.Required("enforce", "body", bool(m.Enforce)); err != nil {
		return err
	}

	return nil
}

func (m *NetworkEntitlements) validateEntitlements(formats strfmt.Registry) error {

	if err := validate.Required("entitlements", "body", m.Entitlements); err != nil {
		return err
	}

	for i := 0; i < len(m.Entitlements); i++ {
		if swag.IsZero(m.Entitlements[i]) { // not required
			continue
		}

		if m.Entitlements[i] != nil {
			if err := m.Entitlements[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("entitlements" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("entitlements" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *NetworkEntitlements) validateNetworkID(formats strfmt.Registry) error {

	if err := validate.RequiredString("network_id", "body", m.NetworkID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this network entitlements based on the context it is used
func (m *NetworkEntitlements) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateEntitlements(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NetworkEntitlements) contextValidateEntitlements(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Entitlements); i++ {

		if m.Entitlements[i] != nil {
			if err := m.Entitlements[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("entitlements" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("entitlements" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *NetworkEntitlements) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NetworkEntitlements) UnmarshalBinary(b []byte) error {
	var res NetworkEntitlements
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
