# Copyright 2026 The Magma Authors.

# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


load("@python_deps//:requirements.bzl", "requirement")
load("//bazel:python_test.bzl", "pytest_test")

MAGMA_ROOT = "../../../../../../"

ORC8R_ROOT = "{}orc8r/gateway/python".format(MAGMA_ROOT)

LTE_ROOT = "{}lte/gateway/python".format(MAGMA_ROOT)

pytest_test(
    name = "test_acsd",
    size = "small",
    srcs = ["test_acsd.py"],
    imports = [
        LTE_ROOT,
        ORC8R_ROOT,
    ],
    deps = [
        "//lte/gateway/python/magma/acsd/datamodel",
        "//lte/gateway/python/magma/acsd:acsd_identity",
        "//lte/gateway/python/magma/acsd:acsd_lib",
        "//lte/gateway/python/magma/acsd:acsd_main",
        "//lte/gateway/python/magma/acsd:digest",
        "//lte/gateway/python/magma/acsd:session",
        "//lte/gateway/python/magma/acsd:store",
        "//lte/gateway/python/magma/acsd:tasks",
        "//lte/protos:mconfigs_python_proto",
        requirement("fakeredis"),
        requirement("protobuf"),
        requirement("pyyaml"),
    ],
)

pytest_test(
    name = "test_session",
    size = "small",
    srcs = ["test_session.py"],
    imports = [
        LTE_ROOT,
        ORC8R_ROOT,
    ],
    deps = [
        "//lte/gateway/python/magma/acsd:session",
        "//lte/gateway/python/magma/acsd:store",
        "//lte/gateway/python/magma/tr069:models",
        requirement("fakeredis"),
    ],
)

pytest_test(
    name = "test_server",
    size = "small",
    srcs = ["test_server.py"],
    data = glob(["fixtures/*.xml"]),
    imports = [
        LTE_ROOT,
        ORC8R_ROOT,
    ],
    deps = [
        "//lte/gateway/python/magma/acsd:acsd_lib",
        "//lte/gateway/python/magma/acsd:server",
        "//lte/gateway/python/magma/acsd:session",
        "//lte/gateway/python/magma/acsd:store",
        requirement("fakeredis"),
    ],
)

pytest_test(
    name = "test_identity",
    size = "small",
    srcs = ["test_identity.py"],
    imports = [
        LTE_ROOT,
        ORC8R_ROOT,
    ],
    deps = [
        "//lte/gateway/python/magma/acsd:acsd_identity",
        "//lte/protos:mobilityd_python_proto",
        "//lte/protos:subscriberdb_python_proto",
        requirement("grpcio"),
    ],
)

pytest_test(
    name = "test_bindings",
    size = "small",
    srcs = ["test_bindings.py"],
    imports = [
        LTE_ROOT,
        ORC8R_ROOT,
    ],
    deps = ["//lte/gateway/python/magma/acsd:acsd_identity"],
)

pytest_test(
    name = "test_session_identity",
    size = "small",
    srcs = ["test_session_identity.py"],
    data = glob(["fixtures/*.xml"]),
    imports = [
        LTE_ROOT,
        ORC8R_ROOT,
    ],
    deps = [
        "//lte/gateway/python/magma/acsd:acsd_identity",
        "//lte/gateway/python/magma/acsd:acsd_lib",
        "//lte/gateway/python/magma/acsd:server",
        "//lte/gateway/python/magma/acsd:session",
        "//lte/gateway/python/magma/acsd:store",
        "//lte/gateway/python/magma/tr069:models",
        "//lte/protos:subscriberdb_python_proto",
        requirement("fakeredis"),
        requirement("grpcio"),
    ],
)

pytest_test(
    name = "test_store",
    size = "small",
    srcs = ["test_store.py"],
    imports = [
        LTE_ROOT,
        ORC8R_ROOT,
    ],
    deps = [
        "//lte/gateway/python/magma/acsd:store",
        requirement("fakeredis"),
    ],
)

pytest_test(
    name = "test_tasks",
    size = "small",
    srcs = ["test_tasks.py"],
    imports = [
        LTE_ROOT,
        ORC8R_ROOT,
    ],
    deps = [
        "//lte/gateway/python/magma/acsd/datamodel",
        "//lte/gateway/python/magma/acsd:store",
        "//lte/gateway/python/magma/acsd:tasks",
        "//lte/gateway/python/magma/tr069:models",
        requirement("fakeredis"),
    ],
)

pytest_test(
    name = "test_session_tasks",
    size = "small",
    srcs = ["test_session_tasks.py"],
    data = glob(["fixtures/*.xml"]),
    imports = [
        LTE_ROOT,
        ORC8R_ROOT,
    ],
    deps = [
        "//lte/gateway/python/magma/acsd/datamodel",
        "//lte/gateway/python/magma/acsd:acsd_lib",
        "//lte/gateway/python/magma/acsd:server",
        "//lte/gateway/python/magma/acsd:session",
        "//lte/gateway/python/magma/acsd:store",
        "//lte/gateway/python/magma/acsd:tasks",
        "//lte/gateway/python/magma/tr069:models",
        requirement("fakeredis"),
    ],
)

pytest_test(
    name = "test_digest",
    size = "small",
    srcs = ["test_digest.py"],
    data = glob(["fixtures/*.xml"]),
    imports = [
        LTE_ROOT,
        ORC8R_ROOT,
    ],
    deps = [
        "//lte/gateway/python/magma/acsd:acsd_lib",
        "//lte/gateway/python/magma/acsd:digest",
        "//lte/gateway/python/magma/acsd:server",
        "//lte/gateway/python/magma/acsd:session",
        "//lte/gateway/python/magma/acsd:store",
        requirement("fakeredis"),
    ],
)

pytest_test(
    name = "test_datamodel_spec",
    size = "small",
    srcs = ["test_datamodel_spec.py"],
    imports = [
        LTE_ROOT,
        ORC8R_ROOT,
    ],
    deps = ["//lte/gateway/python/magma/acsd/datamodel"],
)

pytest_test(
    name = "test_datamodel_registry",
    size = "small",
    srcs = ["test_datamodel_registry.py"],
    data = glob(["fixtures/*.xml"]),
    imports = [
        LTE_ROOT,
        ORC8R_ROOT,
    ],
    deps = [
        "//lte/gateway/python/magma/acsd:server",
        "//lte/gateway/python/magma/acsd/datamodel",
        "//lte/gateway/python/magma/tr069:models",
    ],
)

pytest_test(
    name = "test_session_model",
    size = "small",
    srcs = ["test_session_model.py"],
    imports = [
        LTE_ROOT,
        ORC8R_ROOT,
    ],
    deps = [
        "//lte/gateway/python/magma/acsd:session",
        "//lte/gateway/python/magma/acsd:store",
        "//lte/gateway/python/magma/acsd:tasks",
        "//lte/gateway/python/magma/acsd/datamodel",
        "//lte/gateway/python/magma/tr069:models",
        requirement("fakeredis"),
    ],
)

pytest_test(
    name = "test_claims",
    size = "small",
    srcs = ["test_claims.py"],
    imports = [
        LTE_ROOT,
        ORC8R_ROOT,
    ],
    deps = [
        "//lte/gateway/python/magma/acsd:claims",
        requirement("fakeredis"),
    ],
)

pytest_test(
    name = "test_credentials",
    size = "small",
    srcs = ["test_credentials.py"],
    imports = [
        LTE_ROOT,
        ORC8R_ROOT,
    ],
    deps = [
        "//lte/gateway/python/magma/acsd:credentials",
        "//lte/gateway/python/magma/acsd:digest",
        requirement("fakeredis"),
    ],
)

pytest_test(
    name = "test_claimed",
    size = "small",
    srcs = ["test_claimed.py"],
    imports = [
        LTE_ROOT,
        ORC8R_ROOT,
    ],
    deps = [
        "//lte/gateway/python/magma/acsd:acsd_lib",
        "//lte/gateway/python/magma/acsd:claimed",
        "//lte/gateway/python/magma/acsd:claims",
        "//lte/gateway/python/magma/acsd:credentials",
        "//lte/gateway/python/magma/acsd:digest",
        "//lte/gateway/python/magma/acsd:session",
        "//lte/gateway/python/magma/acsd:store",
        "//lte/gateway/python/magma/acsd:tasks",
        "//lte/gateway/python/magma/acsd/datamodel",
        "//lte/gateway/python/magma/tr069:models",
        requirement("fakeredis"),
    ],
)

pytest_test(
    name = "test_wan_listener",
    size = "small",
    srcs = ["test_wan_listener.py"],
    data = glob(["fixtures/*.xml"]),
    imports = [
        LTE_ROOT,
        ORC8R_ROOT,
    ],
    deps = [
        "//lte/gateway/python/magma/acsd:acsd_lib",
        "//lte/gateway/python/magma/acsd:acsd_main",
        "//lte/gateway/python/magma/acsd:claimed",
        "//lte/gateway/python/magma/acsd:claims",
        "//lte/gateway/python/magma/acsd:credentials",
        "//lte/gateway/python/magma/acsd:digest",
        "//lte/gateway/python/magma/acsd:session",
        "//lte/gateway/python/magma/acsd:store",
        "//lte/protos:mconfigs_python_proto",
        requirement("fakeredis"),
    ],
)

pytest_test(
    name = "test_cli",
    size = "small",
    srcs = ["test_cli.py"],
    imports = [
        LTE_ROOT,
        ORC8R_ROOT,
    ],
    deps = [
        "//lte/gateway/python/magma/acsd:claims",
        "//lte/gateway/python/magma/acsd:cli",
        "//lte/gateway/python/magma/acsd:credentials",
        requirement("fakeredis"),
    ],
)

pytest_test(
    name = "test_session_outcome",
    size = "small",
    srcs = ["test_session_outcome.py"],
    imports = [
        LTE_ROOT,
        ORC8R_ROOT,
    ],
    deps = [
        "//lte/gateway/python/magma/acsd:session",
        "//lte/gateway/python/magma/acsd:store",
        "//lte/gateway/python/magma/acsd:tasks",
        "//lte/gateway/python/magma/tr069:models",
        requirement("fakeredis"),
    ],
)

pytest_test(
    name = "test_cpe_state",
    size = "small",
    srcs = ["test_cpe_state.py"],
    imports = [
        LTE_ROOT,
        ORC8R_ROOT,
    ],
    deps = [
        "//lte/gateway/python/magma/acsd:acsd_lib",
        "//lte/gateway/python/magma/acsd:acsd_main",
        "//lte/gateway/python/magma/acsd:cpe_state",
        "//lte/gateway/python/magma/acsd:store",
        "//lte/gateway/python/magma/acsd:tasks",
        "//lte/protos:mconfigs_python_proto",
        requirement("fakeredis"),
    ],
)

pytest_test(
    name = "test_rpc_servicer",
    size = "small",
    srcs = ["test_rpc_servicer.py"],
    imports = [
        LTE_ROOT,
        ORC8R_ROOT,
    ],
    deps = [
        "//lte/gateway/python/magma/acsd:acsd_lib",
        "//lte/gateway/python/magma/acsd:acsd_main",
        "//lte/gateway/python/magma/acsd:cpe_state",
        "//lte/gateway/python/magma/acsd:rpc_servicer",
        "//lte/gateway/python/magma/acsd:store",
        "//lte/gateway/python/magma/acsd:tasks",
        "//lte/protos:cpe_acs_python_grpc",
        "//lte/protos:cpe_acs_python_proto",
        "//lte/protos:mconfigs_python_proto",
        requirement("fakeredis"),
        requirement("grpcio"),
    ],
)

pytest_test(
    name = "test_metrics",
    size = "small",
    srcs = ["test_metrics.py"],
    imports = [
        LTE_ROOT,
        ORC8R_ROOT,
    ],
    deps = [
        "//lte/gateway/python/magma/acsd:cpe_state",
        "//lte/gateway/python/magma/acsd:metrics",
        "//lte/gateway/python/magma/acsd:session",
        "//lte/gateway/python/magma/acsd:store",
        "//lte/gateway/python/magma/acsd:tasks",
        "//lte/gateway/python/magma/tr069:models",
        requirement("fakeredis"),
        requirement("prometheus_client"),
        requirement("pyyaml"),
    ],
)

pytest_test(
    name = "test_events",
    size = "small",
    srcs = ["test_events.py"],
    imports = [
        LTE_ROOT,
        ORC8R_ROOT,
    ],
    deps = [
        "//lte/gateway/python/magma/acsd:acsd_lib",
        "//lte/gateway/python/magma/acsd:acsd_main",
        "//lte/gateway/python/magma/acsd:cpe_state",
        "//lte/gateway/python/magma/acsd:events",
        "//lte/gateway/python/magma/acsd:store",
        "//lte/gateway/python/magma/acsd:tasks",
        "//lte/protos:mconfigs_python_proto",
        requirement("fakeredis"),
        requirement("prometheus_client"),
        requirement("pyyaml"),
    ],
)
