// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AcsConnectionRequest What acsd did with a Connection Request
//
// swagger:model acs_connection_request
type AcsConnectionRequest struct {

	// Why it failed, the HTTP status or the error
	Detail string `json:"detail,omitempty"`

	// next inform
	// Format: date-time
	NextInform *strfmt.DateTime `json:"next_inform,omitempty"`

	// next_inform when not sent, or connection_request with reason in_session when the CPE has a session open
	//
	Reach string `json:"reach,omitempty"`

	// reason
	Reason string `json:"reason,omitempty"`

	// The CPE accepted it and should open a session now
	// Required: true
	Sent bool `json:"sent"`
}

// Validate validates this acs connection request
func (m *AcsConnectionRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNextInform(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSent(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AcsConnectionRequest) validateNextInform(formats strfmt.Registry) error {
	if swag.IsZero(m.NextInform) { // not required
		return nil
	}

	if err := validate.FormatOf("next_inform", "body", "date-time", m.NextInform.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *AcsConnectionRequest) validateSent(formats strfmt.Registry) error {

	if err := validate.Required("sent", "body", bool(m.Sent)); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this acs connection request based on context it is used
func (m *AcsConnectionRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AcsConnectionRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AcsConnectionRequest) UnmarshalBinary(b []byte) error {
	var res AcsConnectionRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
