// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AcsSessionLog One CWMP exchange of a CPE
//
// swagger:model acs_session_log
type AcsSessionLog struct {

	// The session authenticated with the bootstrap credentials
	Bootstrap bool `json:"bootstrap,omitempty"`

	// device id
	DeviceID string `json:"device_id,omitempty"`

	// Time the ACS took to handle the request
	DurationMs int64 `json:"duration_ms,omitempty"`

	// event
	// Required: true
	// Enum: [inform rpc session_end auth_failure rate_limited]
	Event *string `json:"event"`

	// Inform event codes, e.g. 2 PERIODIC
	EventCodes []string `json:"event_codes"`

	// fault code
	FaultCode int64 `json:"fault_code,omitempty"`

	// fault string
	FaultString string `json:"fault_string,omitempty"`

	// Data model handler serving the CPE
	Handler string `json:"handler,omitempty"`

	// network id
	NetworkID string `json:"network_id,omitempty"`

	// Why the request was refused
	Reason string `json:"reason,omitempty"`

	// The CPE request, or the ACS request the CPE answered
	RPC string `json:"rpc,omitempty"`

	// ACS requests sent in the session, on session_end
	RPCCount int64 `json:"rpc_count,omitempty"`

	// Length of the session, on session_end
	SessionDurationSec int64 `json:"session_duration_sec,omitempty"`

	// session id
	SessionID string `json:"session_id,omitempty"`

	// source ip
	SourceIP string `json:"source_ip,omitempty"`

	// task id
	TaskID string `json:"task_id,omitempty"`

	// task type
	TaskType string `json:"task_type,omitempty"`

	// time
	// Required: true
	// Format: date-time
	Time *strfmt.DateTime `json:"time"`
}

// Validate validates this acs session log
func (m *AcsSessionLog) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEvent(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTime(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var acsSessionLogTypeEventPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["inform","rpc","session_end","auth_failure","rate_limited"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		acsSessionLogTypeEventPropEnum = append(acsSessionLogTypeEventPropEnum, v)
	}
}

const (

	// AcsSessionLogEventInform captures enum value "inform"
	AcsSessionLogEventInform string = "inform"

	// AcsSessionLogEventRPC captures enum value "rpc"
	AcsSessionLogEventRPC string = "rpc"

	// AcsSessionLogEventSessionEnd captures enum value "session_end"
	AcsSessionLogEventSessionEnd string = "session_end"

	// AcsSessionLogEventAuthFailure captures enum value "auth_failure"
	AcsSessionLogEventAuthFailure string = "auth_failure"

	// AcsSessionLogEventRateLimited captures enum value "rate_limited"
	AcsSessionLogEventRateLimited string = "rate_limited"
)

// prop value enum
func (m *AcsSessionLog) validateEventEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, acsSessionLogTypeEventPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *AcsSessionLog) validateEvent(formats strfmt.Registry) error {

	if err := validate.Required("event", "body", m.Event); err != nil {
		return err
	}

	// value enum
	if err := m.validateEventEnum("event", "body", *m.Event); err != nil {
		return err
	}

	return nil
}

func (m *AcsSessionLog) validateTime(formats strfmt.Registry) error {

	if err := validate.Required("time", "body", m.Time); err != nil {
		return err
	}

	if err := validate.FormatOf("time", "body", "date-time", m.Time.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this acs session log based on context it is used
func (m *AcsSessionLog) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AcsSessionLog) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AcsSessionLog) UnmarshalBinary(b []byte) error {
	var res AcsSessionLog
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
