// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AcsDevice A TR-069 CPE known to the ACS
//
// swagger:model acs_device
type AcsDevice struct {

	// TR-069 DeviceId as OUI-ProductClass-SerialNumber
	// Example: 00259E-Titan4000-ABC123456
	// Required: true
	// Min Length: 1
	DeviceID string `json:"device_id"`

	// Software version reported by the CPE
	Firmware string `json:"firmware,omitempty"`

	// first seen
	// Required: true
	// Format: date-time
	FirstSeen strfmt.DateTime `json:"first_seen"`

	// Model handler the ACS uses for this CPE
	Handler string `json:"handler,omitempty"`

	// When the CPE last sent an Inform
	// Required: true
	// Format: date-time
	LastSeen strfmt.DateTime `json:"last_seen"`

	// model
	Model string `json:"model,omitempty"`

	// Whether the last Inform is at most online_interval_multiple periodic inform intervals old (the service config; 2 by default, with online_default_interval_sec standing in for an unknown interval)
	//
	// Required: true
	Online bool `json:"online"`

	// oui
	// Example: 00259E
	// Required: true
	Oui string `json:"oui"`

	// PeriodicInformInterval in seconds the CPE last reported; absent while unknown
	PeriodicInformInterval int64 `json:"periodic_inform_interval,omitempty"`

	// product class
	// Example: Titan4000
	ProductClass string `json:"product_class,omitempty"`

	// serial number
	// Example: ABC123456
	// Required: true
	SerialNumber string `json:"serial_number"`
}

// Validate validates this acs device
func (m *AcsDevice) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDeviceID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFirstSeen(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLastSeen(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOnline(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOui(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSerialNumber(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AcsDevice) validateDeviceID(formats strfmt.Registry) error {

	if err := validate.RequiredString("device_id", "body", m.DeviceID); err != nil {
		return err
	}

	if err := validate.MinLength("device_id", "body", m.DeviceID, 1); err != nil {
		return err
	}

	return nil
}

func (m *AcsDevice) validateFirstSeen(formats strfmt.Registry) error {

	if err := validate.Required("first_seen", "body", strfmt.DateTime(m.FirstSeen)); err != nil {
		return err
	}

	if err := validate.FormatOf("first_seen", "body", "date-time", m.FirstSeen.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *AcsDevice) validateLastSeen(formats strfmt.Registry) error {

	if err := validate.Required("last_seen", "body", strfmt.DateTime(m.LastSeen)); err != nil {
		return err
	}

	if err := validate.FormatOf("last_seen", "body", "date-time", m.LastSeen.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *AcsDevice) validateOnline(formats strfmt.Registry) error {

	if err := validate.Required("online", "body", bool(m.Online)); err != nil {
		return err
	}

	return nil
}

func (m *AcsDevice) validateOui(formats strfmt.Registry) error {

	if err := validate.RequiredString("oui", "body", m.Oui); err != nil {
		return err
	}

	return nil
}

func (m *AcsDevice) validateSerialNumber(formats strfmt.Registry) error {

	if err := validate.RequiredString("serial_number", "body", m.SerialNumber); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this acs device based on context it is used
func (m *AcsDevice) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AcsDevice) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AcsDevice) UnmarshalBinary(b []byte) error {
	var res AcsDevice
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
