// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AcsTaskRequest An operation to run on a CPE in its next session
//
// swagger:model acs_task_request
type AcsTaskRequest struct {

	// Sessions the task may be tried in; the service default when 0
	// Minimum: 0
	MaxAttempts *int64 `json:"max_attempts,omitempty"`

	// List only the direct children of parameter_path
	NextLevel bool `json:"next_level,omitempty"`

	// Parameters or partial paths to read (get_parameter_values)
	ParameterNames []string `json:"parameter_names"`

	// Path to list (get_parameter_names); the data model root when empty
	ParameterPath string `json:"parameter_path,omitempty"`

	// Values to set (set_parameter_values)
	ParameterValues []AcsParameterValue `json:"parameter_values"`

	// Seconds after which a task not yet run expires; the service default when 0
	// Minimum: 0
	TTLSec *int64 `json:"ttl_sec,omitempty"`

	// type
	// Required: true
	// Enum: [reboot factory_reset refresh get_parameter_values set_parameter_values get_parameter_names]
	Type string `json:"type"`
}

// Validate validates this acs task request
func (m *AcsTaskRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMaxAttempts(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateParameterValues(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTTLSec(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AcsTaskRequest) validateMaxAttempts(formats strfmt.Registry) error {
	if swag.IsZero(m.MaxAttempts) { // not required
		return nil
	}

	if err := validate.MinimumInt("max_attempts", "body", *m.MaxAttempts, 0, false); err != nil {
		return err
	}

	return nil
}

func (m *AcsTaskRequest) validateParameterValues(formats strfmt.Registry) error {
	if swag.IsZero(m.ParameterValues) { // not required
		return nil
	}

	for i := 0; i < len(m.ParameterValues); i++ {

		if err := m.ParameterValues[i].Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("parameter_values" + "." + strconv.Itoa(i))
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("parameter_values" + "." + strconv.Itoa(i))
			}
			return err
		}

	}

	return nil
}

func (m *AcsTaskRequest) validateTTLSec(formats strfmt.Registry) error {
	if swag.IsZero(m.TTLSec) { // not required
		return nil
	}

	if err := validate.MinimumInt("ttl_sec", "body", *m.TTLSec, 0, false); err != nil {
		return err
	}

	return nil
}

var acsTaskRequestTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["reboot","factory_reset","refresh","get_parameter_values","set_parameter_values","get_parameter_names"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		acsTaskRequestTypeTypePropEnum = append(acsTaskRequestTypeTypePropEnum, v)
	}
}

const (

	// AcsTaskRequestTypeReboot captures enum value "reboot"
	AcsTaskRequestTypeReboot string = "reboot"

	// AcsTaskRequestTypeFactoryReset captures enum value "factory_reset"
	AcsTaskRequestTypeFactoryReset string = "factory_reset"

	// AcsTaskRequestTypeRefresh captures enum value "refresh"
	AcsTaskRequestTypeRefresh string = "refresh"

	// AcsTaskRequestTypeGetParameterValues captures enum value "get_parameter_values"
	AcsTaskRequestTypeGetParameterValues string = "get_parameter_values"

	// AcsTaskRequestTypeSetParameterValues captures enum value "set_parameter_values"
	AcsTaskRequestTypeSetParameterValues string = "set_parameter_values"

	// AcsTaskRequestTypeGetParameterNames captures enum value "get_parameter_names"
	AcsTaskRequestTypeGetParameterNames string = "get_parameter_names"
)

// prop value enum
func (m *AcsTaskRequest) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, acsTaskRequestTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *AcsTaskRequest) validateType(formats strfmt.Registry) error {

	if err := validate.RequiredString("type", "body", m.Type); err != nil {
		return err
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this acs task request based on the context it is used
func (m *AcsTaskRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateParameterValues(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AcsTaskRequest) contextValidateParameterValues(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ParameterValues); i++ {

		if err := m.ParameterValues[i].ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("parameter_values" + "." + strconv.Itoa(i))
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("parameter_values" + "." + strconv.Itoa(i))
			}
			return err
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *AcsTaskRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AcsTaskRequest) UnmarshalBinary(b []byte) error {
	var res AcsTaskRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
