// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AcsParameterValue A TR-069 parameter and the value to set
//
// swagger:model acs_parameter_value
type AcsParameterValue struct {

	// name
	// Example: Device.ManagementServer.PeriodicInformInterval
	// Required: true
	// Min Length: 1
	Name string `json:"name"`

	// xsd type of the value, xsd:string when empty
	// Example: xsd:unsignedInt
	Type string `json:"type,omitempty"`

	// value
	// Example: 300
	// Required: true
	Value string `json:"value"`
}

// Validate validates this acs parameter value
func (m *AcsParameterValue) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AcsParameterValue) validateName(formats strfmt.Registry) error {

	if err := validate.RequiredString("name", "body", m.Name); err != nil {
		return err
	}

	if err := validate.MinLength("name", "body", m.Name, 1); err != nil {
		return err
	}

	return nil
}

func (m *AcsParameterValue) validateValue(formats strfmt.Registry) error {

	if err := validate.RequiredString("value", "body", m.Value); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this acs parameter value based on context it is used
func (m *AcsParameterValue) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AcsParameterValue) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AcsParameterValue) UnmarshalBinary(b []byte) error {
	var res AcsParameterValue
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
