// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AcsCpeDetail A CPE with its normalized model
//
// swagger:model acs_cpe_detail
type AcsCpeDetail struct {

	// cpe
	// Required: true
	Cpe AcsCpe `json:"cpe"`

	// Vendor-independent model of the CPE (identity, cellular, wan, management_server, ...)
	//
	Model interface{} `json:"model,omitempty"`
}

// Validate validates this acs cpe detail
func (m *AcsCpeDetail) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCpe(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AcsCpeDetail) validateCpe(formats strfmt.Registry) error {

	if err := m.Cpe.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("cpe")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("cpe")
		}
		return err
	}

	return nil
}

// ContextValidate validate this acs cpe detail based on the context it is used
func (m *AcsCpeDetail) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCpe(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AcsCpeDetail) contextValidateCpe(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Cpe.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("cpe")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("cpe")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AcsCpeDetail) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AcsCpeDetail) UnmarshalBinary(b []byte) error {
	var res AcsCpeDetail
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
