// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AcsLog One acsd event. Session fields are set on cpe_session_completed, task fields on cpe_task_failed (lte/swagger/cpe_acs_events.v1.yml).
//
// swagger:model acs_log
type AcsLog struct {

	// attempts
	Attempts int32 `json:"attempts,omitempty"`

	// cpe key
	// Required: true
	CpeKey string `json:"cpe_key"`

	// ended
	// Format: date-time
	Ended *strfmt.DateTime `json:"ended,omitempty"`

	// event
	// Required: true
	// Enum: [cpe_session_completed cpe_task_failed]
	Event string `json:"event"`

	// 0 when the task failed because its sessions kept dropping
	FaultCode int32 `json:"fault_code,omitempty"`

	// fault string
	FaultString string `json:"fault_string,omitempty"`

	// faults
	Faults int32 `json:"faults,omitempty"`

	// gateway id
	GatewayID string `json:"gateway_id,omitempty"`

	// hardware id
	HardwareID string `json:"hardware_id,omitempty"`

	// Empty when acsd does not know the CPE's IMSI
	Imsi string `json:"imsi,omitempty"`

	// max attempts
	MaxAttempts int32 `json:"max_attempts,omitempty"`

	// reason
	Reason string `json:"reason,omitempty"`

	// completed, timed_out or interrupted
	Result string `json:"result,omitempty"`

	// session id
	SessionID string `json:"session_id,omitempty"`

	// started
	// Format: date-time
	Started *strfmt.DateTime `json:"started,omitempty"`

	// task id
	TaskID string `json:"task_id,omitempty"`

	// task type
	TaskType string `json:"task_type,omitempty"`

	// tasks done
	TasksDone int32 `json:"tasks_done,omitempty"`

	// tasks failed
	TasksFailed int32 `json:"tasks_failed,omitempty"`

	// When eventd received the event
	// Required: true
	// Format: date-time
	Time strfmt.DateTime `json:"time"`
}

// Validate validates this acs log
func (m *AcsLog) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCpeKey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEnded(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEvent(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStarted(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTime(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AcsLog) validateCpeKey(formats strfmt.Registry) error {

	if err := validate.RequiredString("cpe_key", "body", m.CpeKey); err != nil {
		return err
	}

	return nil
}

func (m *AcsLog) validateEnded(formats strfmt.Registry) error {
	if swag.IsZero(m.Ended) { // not required
		return nil
	}

	if err := validate.FormatOf("ended", "body", "date-time", m.Ended.String(), formats); err != nil {
		return err
	}

	return nil
}

var acsLogTypeEventPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["cpe_session_completed","cpe_task_failed"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		acsLogTypeEventPropEnum = append(acsLogTypeEventPropEnum, v)
	}
}

const (

	// AcsLogEventCpeSessionCompleted captures enum value "cpe_session_completed"
	AcsLogEventCpeSessionCompleted string = "cpe_session_completed"

	// AcsLogEventCpeTaskFailed captures enum value "cpe_task_failed"
	AcsLogEventCpeTaskFailed string = "cpe_task_failed"
)

// prop value enum
func (m *AcsLog) validateEventEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, acsLogTypeEventPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *AcsLog) validateEvent(formats strfmt.Registry) error {

	if err := validate.RequiredString("event", "body", m.Event); err != nil {
		return err
	}

	// value enum
	if err := m.validateEventEnum("event", "body", m.Event); err != nil {
		return err
	}

	return nil
}

func (m *AcsLog) validateStarted(formats strfmt.Registry) error {
	if swag.IsZero(m.Started) { // not required
		return nil
	}

	if err := validate.FormatOf("started", "body", "date-time", m.Started.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *AcsLog) validateTime(formats strfmt.Registry) error {

	if err := validate.Required("time", "body", strfmt.DateTime(m.Time)); err != nil {
		return err
	}

	if err := validate.FormatOf("time", "body", "date-time", m.Time.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this acs log based on context it is used
func (m *AcsLog) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AcsLog) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AcsLog) UnmarshalBinary(b []byte) error {
	var res AcsLog
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
