// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AcsTask An operation queued for a CPE
//
// swagger:model acs_task
type AcsTask struct {

	// attempts
	// Required: true
	Attempts int64 `json:"attempts"`

	// created
	// Required: true
	// Format: date-time
	Created strfmt.DateTime `json:"created"`

	// deadline
	// Format: date-time
	Deadline strfmt.DateTime `json:"deadline,omitempty"`

	// device id
	// Required: true
	DeviceID string `json:"device_id"`

	// CWMP fault code of the last failed attempt
	FaultCode int64 `json:"fault_code,omitempty"`

	// fault string
	FaultString string `json:"fault_string,omitempty"`

	// id
	// Required: true
	ID string `json:"id"`

	// max attempts
	// Required: true
	MaxAttempts int64 `json:"max_attempts"`

	// next level
	NextLevel bool `json:"next_level,omitempty"`

	// parameter names
	ParameterNames []string `json:"parameter_names"`

	// parameter path
	ParameterPath string `json:"parameter_path,omitempty"`

	// parameter values
	ParameterValues []AcsParameterValue `json:"parameter_values"`

	// What the CPE returned (values, names, status) and faults the task tolerated
	Result interface{} `json:"result,omitempty"`

	// status
	// Required: true
	// Enum: [pending in_progress done failed expired]
	Status string `json:"status"`

	// type
	// Required: true
	Type string `json:"type"`

	// updated
	// Required: true
	// Format: date-time
	Updated strfmt.DateTime `json:"updated"`
}

// Validate validates this acs task
func (m *AcsTask) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAttempts(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreated(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDeadline(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDeviceID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMaxAttempts(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateParameterValues(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdated(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AcsTask) validateAttempts(formats strfmt.Registry) error {

	if err := validate.Required("attempts", "body", int64(m.Attempts)); err != nil {
		return err
	}

	return nil
}

func (m *AcsTask) validateCreated(formats strfmt.Registry) error {

	if err := validate.Required("created", "body", strfmt.DateTime(m.Created)); err != nil {
		return err
	}

	if err := validate.FormatOf("created", "body", "date-time", m.Created.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *AcsTask) validateDeadline(formats strfmt.Registry) error {
	if swag.IsZero(m.Deadline) { // not required
		return nil
	}

	if err := validate.FormatOf("deadline", "body", "date-time", m.Deadline.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *AcsTask) validateDeviceID(formats strfmt.Registry) error {

	if err := validate.RequiredString("device_id", "body", m.DeviceID); err != nil {
		return err
	}

	return nil
}

func (m *AcsTask) validateID(formats strfmt.Registry) error {

	if err := validate.RequiredString("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *AcsTask) validateMaxAttempts(formats strfmt.Registry) error {

	if err := validate.Required("max_attempts", "body", int64(m.MaxAttempts)); err != nil {
		return err
	}

	return nil
}

func (m *AcsTask) validateParameterValues(formats strfmt.Registry) error {
	if swag.IsZero(m.ParameterValues) { // not required
		return nil
	}

	for i := 0; i < len(m.ParameterValues); i++ {

		if err := m.ParameterValues[i].Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("parameter_values" + "." + strconv.Itoa(i))
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("parameter_values" + "." + strconv.Itoa(i))
			}
			return err
		}

	}

	return nil
}

var acsTaskTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["pending","in_progress","done","failed","expired"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		acsTaskTypeStatusPropEnum = append(acsTaskTypeStatusPropEnum, v)
	}
}

const (

	// AcsTaskStatusPending captures enum value "pending"
	AcsTaskStatusPending string = "pending"

	// AcsTaskStatusInProgress captures enum value "in_progress"
	AcsTaskStatusInProgress string = "in_progress"

	// AcsTaskStatusDone captures enum value "done"
	AcsTaskStatusDone string = "done"

	// AcsTaskStatusFailed captures enum value "failed"
	AcsTaskStatusFailed string = "failed"

	// AcsTaskStatusExpired captures enum value "expired"
	AcsTaskStatusExpired string = "expired"
)

// prop value enum
func (m *AcsTask) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, acsTaskTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *AcsTask) validateStatus(formats strfmt.Registry) error {

	if err := validate.RequiredString("status", "body", m.Status); err != nil {
		return err
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

func (m *AcsTask) validateType(formats strfmt.Registry) error {

	if err := validate.RequiredString("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

func (m *AcsTask) validateUpdated(formats strfmt.Registry) error {

	if err := validate.Required("updated", "body", strfmt.DateTime(m.Updated)); err != nil {
		return err
	}

	if err := validate.FormatOf("updated", "body", "date-time", m.Updated.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this acs task based on the context it is used
func (m *AcsTask) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateParameterValues(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AcsTask) contextValidateParameterValues(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ParameterValues); i++ {

		if err := m.ParameterValues[i].ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("parameter_values" + "." + strconv.Itoa(i))
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("parameter_values" + "." + strconv.Itoa(i))
			}
			return err
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *AcsTask) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AcsTask) UnmarshalBinary(b []byte) error {
	var res AcsTask
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
