// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AcsDeviceDetail A CPE with its last Inform and normalized state
//
// swagger:model acs_device_detail
type AcsDeviceDetail struct {

	// device
	// Required: true
	Device AcsDevice `json:"device"`

	// last inform
	// Required: true
	LastInform AcsInform `json:"last_inform"`

	// Vendor-independent model of the CPE (identity, firmware, cellular KPIs, WAN, management server)
	State interface{} `json:"state,omitempty"`

	// When the state last changed; absent without state
	// Format: date-time
	StateUpdated *strfmt.DateTime `json:"state_updated,omitempty"`
}

// Validate validates this acs device detail
func (m *AcsDeviceDetail) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDevice(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLastInform(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStateUpdated(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AcsDeviceDetail) validateDevice(formats strfmt.Registry) error {

	if err := m.Device.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("device")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("device")
		}
		return err
	}

	return nil
}

func (m *AcsDeviceDetail) validateLastInform(formats strfmt.Registry) error {

	if err := m.LastInform.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("last_inform")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("last_inform")
		}
		return err
	}

	return nil
}

func (m *AcsDeviceDetail) validateStateUpdated(formats strfmt.Registry) error {
	if swag.IsZero(m.StateUpdated) { // not required
		return nil
	}

	if err := validate.FormatOf("state_updated", "body", "date-time", m.StateUpdated.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this acs device detail based on the context it is used
func (m *AcsDeviceDetail) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDevice(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateLastInform(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AcsDeviceDetail) contextValidateDevice(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Device.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("device")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("device")
		}
		return err
	}

	return nil
}

func (m *AcsDeviceDetail) contextValidateLastInform(ctx context.Context, formats strfmt.Registry) error {

	if err := m.LastInform.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("last_inform")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("last_inform")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AcsDeviceDetail) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AcsDeviceDetail) UnmarshalBinary(b []byte) error {
	var res AcsDeviceDetail
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
