// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AcsCpeSession How the last CWMP session of a CPE ended
//
// swagger:model acs_cpe_session
type AcsCpeSession struct {

	// ended
	// Format: date-time
	Ended *strfmt.DateTime `json:"ended,omitempty"`

	// faults
	Faults int32 `json:"faults,omitempty"`

	// reason
	Reason string `json:"reason,omitempty"`

	// completed, timed_out or interrupted
	Result string `json:"result,omitempty"`

	// session id
	SessionID string `json:"session_id,omitempty"`

	// started
	// Format: date-time
	Started *strfmt.DateTime `json:"started,omitempty"`

	// tasks done
	TasksDone int32 `json:"tasks_done,omitempty"`

	// tasks failed
	TasksFailed int32 `json:"tasks_failed,omitempty"`
}

// Validate validates this acs cpe session
func (m *AcsCpeSession) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEnded(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStarted(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AcsCpeSession) validateEnded(formats strfmt.Registry) error {
	if swag.IsZero(m.Ended) { // not required
		return nil
	}

	if err := validate.FormatOf("ended", "body", "date-time", m.Ended.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *AcsCpeSession) validateStarted(formats strfmt.Registry) error {
	if swag.IsZero(m.Started) { // not required
		return nil
	}

	if err := validate.FormatOf("started", "body", "date-time", m.Started.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this acs cpe session based on context it is used
func (m *AcsCpeSession) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AcsCpeSession) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AcsCpeSession) UnmarshalBinary(b []byte) error {
	var res AcsCpeSession
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
