// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AcsCpe A TR-069 CPE as last reported by its AGW
//
// swagger:model acs_cpe
type AcsCpe struct {

	// Other gateways that report this cpe_key online too: a claim ID used on two AGWs, or a CPE that just moved to gateway_id
	//
	ConflictingGatewayIds []string `json:"conflicting_gateway_ids"`

	// cpe key
	// Example: IMSI001010000000001
	// Required: true
	// Min Length: 1
	CpeKey string `json:"cpe_key"`

	// Gateway serving the CPE (the newest Inform); empty if unregistered
	// Required: true
	GatewayID string `json:"gateway_id"`

	// Datamodel handler acsd serves the CPE with
	Handler string `json:"handler,omitempty"`

	// Hardware ID of that gateway
	HardwareID string `json:"hardware_id,omitempty"`

	// Empty when unknown (a claimed CPE that did not report its SIM)
	// Example: IMSI001010000000001
	Imsi string `json:"imsi,omitempty"`

	// informs total
	InformsTotal int64 `json:"informs_total,omitempty"`

	// When the CPE last sent an Inform; absent if never
	// Format: date-time
	LastInform *strfmt.DateTime `json:"last_inform,omitempty"`

	// last session
	LastSession *AcsCpeSession `json:"last_session,omitempty"`

	// mode
	// Required: true
	// Enum: [core claimed]
	Mode string `json:"mode"`

	// ModelName the CPE reported, from the normalized model
	ModelName string `json:"model_name,omitempty"`

	// When the next periodic Inform is due; in the past when the CPE is late, absent before its first Inform
	// Format: date-time
	NextInform *strfmt.DateTime `json:"next_inform,omitempty"`

	// Whether the last Inform is at most two periodic inform intervals old, as acsd computed it; false when the AGW report is stale
	//
	// Required: true
	Online bool `json:"online"`

	// oui
	// Example: 00259E
	Oui string `json:"oui,omitempty"`

	// pending tasks
	PendingTasks int32 `json:"pending_tasks,omitempty"`

	// product class
	// Example: Titan4000
	ProductClass string `json:"product_class,omitempty"`

	// How queued tasks get to the CPE: connection_request (acsd asks the CPE to open a session, the tasks run within seconds) or next_inform (they wait for next_inform); empty when acsd does not say
	//
	Reach string `json:"reach,omitempty"`

	// Why reach is next_inform: behind_nat, no_url, no_credential, disabled, connection_request_failed or frozen
	//
	ReachReason string `json:"reach_reason,omitempty"`

	// When the AGW last reported the CPE's state
	// Required: true
	// Format: date-time
	ReportedAt strfmt.DateTime `json:"reported_at"`

	// serial number
	// Example: ABC123456
	SerialNumber string `json:"serial_number,omitempty"`

	// software version
	SoftwareVersion string `json:"software_version,omitempty"`
}

// Validate validates this acs cpe
func (m *AcsCpe) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCpeKey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGatewayID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLastInform(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLastSession(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNextInform(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOnline(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateReportedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AcsCpe) validateCpeKey(formats strfmt.Registry) error {

	if err := validate.RequiredString("cpe_key", "body", m.CpeKey); err != nil {
		return err
	}

	if err := validate.MinLength("cpe_key", "body", m.CpeKey, 1); err != nil {
		return err
	}

	return nil
}

func (m *AcsCpe) validateGatewayID(formats strfmt.Registry) error {

	if err := validate.RequiredString("gateway_id", "body", m.GatewayID); err != nil {
		return err
	}

	return nil
}

func (m *AcsCpe) validateLastInform(formats strfmt.Registry) error {
	if swag.IsZero(m.LastInform) { // not required
		return nil
	}

	if err := validate.FormatOf("last_inform", "body", "date-time", m.LastInform.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *AcsCpe) validateLastSession(formats strfmt.Registry) error {
	if swag.IsZero(m.LastSession) { // not required
		return nil
	}

	if m.LastSession != nil {
		if err := m.LastSession.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("last_session")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("last_session")
			}
			return err
		}
	}

	return nil
}

var acsCpeTypeModePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["core","claimed"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		acsCpeTypeModePropEnum = append(acsCpeTypeModePropEnum, v)
	}
}

const (

	// AcsCpeModeCore captures enum value "core"
	AcsCpeModeCore string = "core"

	// AcsCpeModeClaimed captures enum value "claimed"
	AcsCpeModeClaimed string = "claimed"
)

// prop value enum
func (m *AcsCpe) validateModeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, acsCpeTypeModePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *AcsCpe) validateMode(formats strfmt.Registry) error {

	if err := validate.RequiredString("mode", "body", m.Mode); err != nil {
		return err
	}

	// value enum
	if err := m.validateModeEnum("mode", "body", m.Mode); err != nil {
		return err
	}

	return nil
}

func (m *AcsCpe) validateNextInform(formats strfmt.Registry) error {
	if swag.IsZero(m.NextInform) { // not required
		return nil
	}

	if err := validate.FormatOf("next_inform", "body", "date-time", m.NextInform.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *AcsCpe) validateOnline(formats strfmt.Registry) error {

	if err := validate.Required("online", "body", bool(m.Online)); err != nil {
		return err
	}

	return nil
}

func (m *AcsCpe) validateReportedAt(formats strfmt.Registry) error {

	if err := validate.Required("reported_at", "body", strfmt.DateTime(m.ReportedAt)); err != nil {
		return err
	}

	if err := validate.FormatOf("reported_at", "body", "date-time", m.ReportedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this acs cpe based on the context it is used
func (m *AcsCpe) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateLastSession(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AcsCpe) contextValidateLastSession(ctx context.Context, formats strfmt.Registry) error {

	if m.LastSession != nil {
		if err := m.LastSession.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("last_session")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("last_session")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AcsCpe) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AcsCpe) UnmarshalBinary(b []byte) error {
	var res AcsCpe
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
