// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AcsTask An operation queued for a CPE
//
// swagger:model acs_task
type AcsTask struct {

	// The arguments the task was queued with
	Args interface{} `json:"args,omitempty"`

	// attempts
	// Required: true
	Attempts int32 `json:"attempts"`

	// cpe key
	// Required: true
	CpeKey string `json:"cpe_key"`

	// created
	// Required: true
	// Format: date-time
	Created strfmt.DateTime `json:"created"`

	// When a task not yet run expires; absent if never
	// Format: date-time
	Deadline *strfmt.DateTime `json:"deadline,omitempty"`

	// CWMP fault code of the last fault; 0 for a requeue after a dropped session
	FaultCode int32 `json:"fault_code,omitempty"`

	// fault string
	FaultString string `json:"fault_string,omitempty"`

	// id
	// Required: true
	ID string `json:"id"`

	// imsi
	Imsi string `json:"imsi,omitempty"`

	// max attempts
	// Required: true
	MaxAttempts int32 `json:"max_attempts"`

	// What the CPE answered (values, names) and faults the task tolerated
	Result interface{} `json:"result,omitempty"`

	// status
	// Required: true
	// Enum: [pending in_progress done failed expired]
	Status string `json:"status"`

	// type
	// Required: true
	// Enum: [reboot factory_reset refresh get_parameter_values set_parameter_values get_parameter_names]
	Type string `json:"type"`

	// updated
	// Required: true
	// Format: date-time
	Updated strfmt.DateTime `json:"updated"`
}

// Validate validates this acs task
func (m *AcsTask) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAttempts(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCpeKey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreated(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDeadline(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMaxAttempts(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdated(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AcsTask) validateAttempts(formats strfmt.Registry) error {

	if err := validate.Required("attempts", "body", int32(m.Attempts)); err != nil {
		return err
	}

	return nil
}

func (m *AcsTask) validateCpeKey(formats strfmt.Registry) error {

	if err := validate.RequiredString("cpe_key", "body", m.CpeKey); err != nil {
		return err
	}

	return nil
}

func (m *AcsTask) validateCreated(formats strfmt.Registry) error {

	if err := validate.Required("created", "body", strfmt.DateTime(m.Created)); err != nil {
		return err
	}

	if err := validate.FormatOf("created", "body", "date-time", m.Created.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *AcsTask) validateDeadline(formats strfmt.Registry) error {
	if swag.IsZero(m.Deadline) { // not required
		return nil
	}

	if err := validate.FormatOf("deadline", "body", "date-time", m.Deadline.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *AcsTask) validateID(formats strfmt.Registry) error {

	if err := validate.RequiredString("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *AcsTask) validateMaxAttempts(formats strfmt.Registry) error {

	if err := validate.Required("max_attempts", "body", int32(m.MaxAttempts)); err != nil {
		return err
	}

	return nil
}

var acsTaskTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["pending","in_progress","done","failed","expired"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		acsTaskTypeStatusPropEnum = append(acsTaskTypeStatusPropEnum, v)
	}
}

const (

	// AcsTaskStatusPending captures enum value "pending"
	AcsTaskStatusPending string = "pending"

	// AcsTaskStatusInProgress captures enum value "in_progress"
	AcsTaskStatusInProgress string = "in_progress"

	// AcsTaskStatusDone captures enum value "done"
	AcsTaskStatusDone string = "done"

	// AcsTaskStatusFailed captures enum value "failed"
	AcsTaskStatusFailed string = "failed"

	// AcsTaskStatusExpired captures enum value "expired"
	AcsTaskStatusExpired string = "expired"
)

// prop value enum
func (m *AcsTask) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, acsTaskTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *AcsTask) validateStatus(formats strfmt.Registry) error {

	if err := validate.RequiredString("status", "body", m.Status); err != nil {
		return err
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

var acsTaskTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["reboot","factory_reset","refresh","get_parameter_values","set_parameter_values","get_parameter_names"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		acsTaskTypeTypePropEnum = append(acsTaskTypeTypePropEnum, v)
	}
}

const (

	// AcsTaskTypeReboot captures enum value "reboot"
	AcsTaskTypeReboot string = "reboot"

	// AcsTaskTypeFactoryReset captures enum value "factory_reset"
	AcsTaskTypeFactoryReset string = "factory_reset"

	// AcsTaskTypeRefresh captures enum value "refresh"
	AcsTaskTypeRefresh string = "refresh"

	// AcsTaskTypeGetParameterValues captures enum value "get_parameter_values"
	AcsTaskTypeGetParameterValues string = "get_parameter_values"

	// AcsTaskTypeSetParameterValues captures enum value "set_parameter_values"
	AcsTaskTypeSetParameterValues string = "set_parameter_values"

	// AcsTaskTypeGetParameterNames captures enum value "get_parameter_names"
	AcsTaskTypeGetParameterNames string = "get_parameter_names"
)

// prop value enum
func (m *AcsTask) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, acsTaskTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *AcsTask) validateType(formats strfmt.Registry) error {

	if err := validate.RequiredString("type", "body", m.Type); err != nil {
		return err
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

func (m *AcsTask) validateUpdated(formats strfmt.Registry) error {

	if err := validate.Required("updated", "body", strfmt.DateTime(m.Updated)); err != nil {
		return err
	}

	if err := validate.FormatOf("updated", "body", "date-time", m.Updated.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this acs task based on context it is used
func (m *AcsTask) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AcsTask) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AcsTask) UnmarshalBinary(b []byte) error {
	var res AcsTask
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
