//
//Copyright 2026 The Magma Authors.
//
//This source code is licensed under the BSD-style license found in the
//LICENSE file in the root directory of this source tree.
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v7.35.0
// source: lte/protos/cpe_acs.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CpeTaskType int32

const (
	CpeTaskType_CPE_TASK_TYPE_UNSPECIFIED   CpeTaskType = 0
	CpeTaskType_CPE_TASK_TYPE_REBOOT        CpeTaskType = 1
	CpeTaskType_CPE_TASK_TYPE_FACTORY_RESET CpeTaskType = 2
	// Read the subtrees of the CPE's datamodel handler into the snapshot.
	CpeTaskType_CPE_TASK_TYPE_REFRESH              CpeTaskType = 3
	CpeTaskType_CPE_TASK_TYPE_GET_PARAMETER_VALUES CpeTaskType = 4
	CpeTaskType_CPE_TASK_TYPE_SET_PARAMETER_VALUES CpeTaskType = 5
	CpeTaskType_CPE_TASK_TYPE_GET_PARAMETER_NAMES  CpeTaskType = 6
)

// Enum value maps for CpeTaskType.
var (
	CpeTaskType_name = map[int32]string{
		0: "CPE_TASK_TYPE_UNSPECIFIED",
		1: "CPE_TASK_TYPE_REBOOT",
		2: "CPE_TASK_TYPE_FACTORY_RESET",
		3: "CPE_TASK_TYPE_REFRESH",
		4: "CPE_TASK_TYPE_GET_PARAMETER_VALUES",
		5: "CPE_TASK_TYPE_SET_PARAMETER_VALUES",
		6: "CPE_TASK_TYPE_GET_PARAMETER_NAMES",
	}
	CpeTaskType_value = map[string]int32{
		"CPE_TASK_TYPE_UNSPECIFIED":          0,
		"CPE_TASK_TYPE_REBOOT":               1,
		"CPE_TASK_TYPE_FACTORY_RESET":        2,
		"CPE_TASK_TYPE_REFRESH":              3,
		"CPE_TASK_TYPE_GET_PARAMETER_VALUES": 4,
		"CPE_TASK_TYPE_SET_PARAMETER_VALUES": 5,
		"CPE_TASK_TYPE_GET_PARAMETER_NAMES":  6,
	}
)

func (x CpeTaskType) Enum() *CpeTaskType {
	p := new(CpeTaskType)
	*p = x
	return p
}

func (x CpeTaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CpeTaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_lte_protos_cpe_acs_proto_enumTypes[0].Descriptor()
}

func (CpeTaskType) Type() protoreflect.EnumType {
	return &file_lte_protos_cpe_acs_proto_enumTypes[0]
}

func (x CpeTaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CpeTaskType.Descriptor instead.
func (CpeTaskType) EnumDescriptor() ([]byte, []int) {
	return file_lte_protos_cpe_acs_proto_rawDescGZIP(), []int{0}
}

type CpeTaskStatus int32

const (
	CpeTaskStatus_CPE_TASK_STATUS_UNSPECIFIED CpeTaskStatus = 0
	CpeTaskStatus_CPE_TASK_STATUS_PENDING     CpeTaskStatus = 1
	CpeTaskStatus_CPE_TASK_STATUS_IN_PROGRESS CpeTaskStatus = 2
	CpeTaskStatus_CPE_TASK_STATUS_DONE        CpeTaskStatus = 3
	CpeTaskStatus_CPE_TASK_STATUS_FAILED      CpeTaskStatus = 4
	CpeTaskStatus_CPE_TASK_STATUS_EXPIRED     CpeTaskStatus = 5
)

// Enum value maps for CpeTaskStatus.
var (
	CpeTaskStatus_name = map[int32]string{
		0: "CPE_TASK_STATUS_UNSPECIFIED",
		1: "CPE_TASK_STATUS_PENDING",
		2: "CPE_TASK_STATUS_IN_PROGRESS",
		3: "CPE_TASK_STATUS_DONE",
		4: "CPE_TASK_STATUS_FAILED",
		5: "CPE_TASK_STATUS_EXPIRED",
	}
	CpeTaskStatus_value = map[string]int32{
		"CPE_TASK_STATUS_UNSPECIFIED": 0,
		"CPE_TASK_STATUS_PENDING":     1,
		"CPE_TASK_STATUS_IN_PROGRESS": 2,
		"CPE_TASK_STATUS_DONE":        3,
		"CPE_TASK_STATUS_FAILED":      4,
		"CPE_TASK_STATUS_EXPIRED":     5,
	}
)

func (x CpeTaskStatus) Enum() *CpeTaskStatus {
	p := new(CpeTaskStatus)
	*p = x
	return p
}

func (x CpeTaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CpeTaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_lte_protos_cpe_acs_proto_enumTypes[1].Descriptor()
}

func (CpeTaskStatus) Type() protoreflect.EnumType {
	return &file_lte_protos_cpe_acs_proto_enumTypes[1]
}

func (x CpeTaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CpeTaskStatus.Descriptor instead.
func (CpeTaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_lte_protos_cpe_acs_proto_rawDescGZIP(), []int{1}
}

type CpeMode int32

const (
	CpeMode_CPE_MODE_UNSPECIFIED CpeMode = 0
	// Keyed by the IMSI behind its source IP on the Magma core.
	CpeMode_CPE_MODE_CORE CpeMode = 1
	// Keyed by a claim; reaches acsd from outside the core.
	CpeMode_CPE_MODE_CLAIMED CpeMode = 2
)

// Enum value maps for CpeMode.
var (
	CpeMode_name = map[int32]string{
		0: "CPE_MODE_UNSPECIFIED",
		1: "CPE_MODE_CORE",
		2: "CPE_MODE_CLAIMED",
	}
	CpeMode_value = map[string]int32{
		"CPE_MODE_UNSPECIFIED": 0,
		"CPE_MODE_CORE":        1,
		"CPE_MODE_CLAIMED":     2,
	}
)

func (x CpeMode) Enum() *CpeMode {
	p := new(CpeMode)
	*p = x
	return p
}

func (x CpeMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CpeMode) Descriptor() protoreflect.EnumDescriptor {
	return file_lte_protos_cpe_acs_proto_enumTypes[2].Descriptor()
}

func (CpeMode) Type() protoreflect.EnumType {
	return &file_lte_protos_cpe_acs_proto_enumTypes[2]
}

func (x CpeMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CpeMode.Descriptor instead.
func (CpeMode) EnumDescriptor() ([]byte, []int) {
	return file_lte_protos_cpe_acs_proto_rawDescGZIP(), []int{2}
}

type CpeParameterValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// xsd type; "xsd:string" when empty.
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *CpeParameterValue) Reset() {
	*x = CpeParameterValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lte_protos_cpe_acs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CpeParameterValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpeParameterValue) ProtoMessage() {}

func (x *CpeParameterValue) ProtoReflect() protoreflect.Message {
	mi := &file_lte_protos_cpe_acs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpeParameterValue.ProtoReflect.Descriptor instead.
func (*CpeParameterValue) Descriptor() ([]byte, []int) {
	return file_lte_protos_cpe_acs_proto_rawDescGZIP(), []int{0}
}

func (x *CpeParameterValue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CpeParameterValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *CpeParameterValue) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type EnqueueTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CpeKey string      `protobuf:"bytes,1,opt,name=cpe_key,json=cpeKey,proto3" json:"cpe_key,omitempty"`
	Type   CpeTaskType `protobuf:"varint,2,opt,name=type,proto3,enum=magma.lte.CpeTaskType" json:"type,omitempty"`
	// GET_PARAMETER_VALUES
	ParameterNames []string `protobuf:"bytes,3,rep,name=parameter_names,json=parameterNames,proto3" json:"parameter_names,omitempty"`
	// SET_PARAMETER_VALUES
	ParameterValues []*CpeParameterValue `protobuf:"bytes,4,rep,name=parameter_values,json=parameterValues,proto3" json:"parameter_values,omitempty"`
	// GET_PARAMETER_NAMES
	ParameterPath string `protobuf:"bytes,5,opt,name=parameter_path,json=parameterPath,proto3" json:"parameter_path,omitempty"`
	NextLevel     bool   `protobuf:"varint,6,opt,name=next_level,json=nextLevel,proto3" json:"next_level,omitempty"`
	// 0 uses acsd's default.
	MaxAttempts int32 `protobuf:"varint,7,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	// 0 uses acsd's default; negative means the task never expires.
	TtlSec int64 `protobuf:"varint,8,opt,name=ttl_sec,json=ttlSec,proto3" json:"ttl_sec,omitempty"`
}

func (x *EnqueueTaskRequest) Reset() {
	*x = EnqueueTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lte_protos_cpe_acs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnqueueTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueTaskRequest) ProtoMessage() {}

func (x *EnqueueTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lte_protos_cpe_acs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueTaskRequest.ProtoReflect.Descriptor instead.
func (*EnqueueTaskRequest) Descriptor() ([]byte, []int) {
	return file_lte_protos_cpe_acs_proto_rawDescGZIP(), []int{1}
}

func (x *EnqueueTaskRequest) GetCpeKey() string {
	if x != nil {
		return x.CpeKey
	}
	return ""
}

func (x *EnqueueTaskRequest) GetType() CpeTaskType {
	if x != nil {
		return x.Type
	}
	return CpeTaskType_CPE_TASK_TYPE_UNSPECIFIED
}

func (x *EnqueueTaskRequest) GetParameterNames() []string {
	if x != nil {
		return x.ParameterNames
	}
	return nil
}

func (x *EnqueueTaskRequest) GetParameterValues() []*CpeParameterValue {
	if x != nil {
		return x.ParameterValues
	}
	return nil
}

func (x *EnqueueTaskRequest) GetParameterPath() string {
	if x != nil {
		return x.ParameterPath
	}
	return ""
}

func (x *EnqueueTaskRequest) GetNextLevel() bool {
	if x != nil {
		return x.NextLevel
	}
	return false
}

func (x *EnqueueTaskRequest) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *EnqueueTaskRequest) GetTtlSec() int64 {
	if x != nil {
		return x.TtlSec
	}
	return 0
}

type CpeTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId string        `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	CpeKey string        `protobuf:"bytes,2,opt,name=cpe_key,json=cpeKey,proto3" json:"cpe_key,omitempty"`
	Type   CpeTaskType   `protobuf:"varint,3,opt,name=type,proto3,enum=magma.lte.CpeTaskType" json:"type,omitempty"`
	Status CpeTaskStatus `protobuf:"varint,4,opt,name=status,proto3,enum=magma.lte.CpeTaskStatus" json:"status,omitempty"`
	// The arguments the task was queued with.
	Args        *structpb.Struct `protobuf:"bytes,5,opt,name=args,proto3" json:"args,omitempty"`
	Attempts    int32            `protobuf:"varint,6,opt,name=attempts,proto3" json:"attempts,omitempty"`
	MaxAttempts int32            `protobuf:"varint,7,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	// Of the last fault; a requeue after a dropped session leaves the
	// reason in fault_string with fault_code 0.
	FaultCode   int32  `protobuf:"varint,8,opt,name=fault_code,json=faultCode,proto3" json:"fault_code,omitempty"`
	FaultString string `protobuf:"bytes,9,opt,name=fault_string,json=faultString,proto3" json:"fault_string,omitempty"`
	// What the CPE answered: "values", "names", tolerated "faults".
	Result *structpb.Struct `protobuf:"bytes,10,opt,name=result,proto3" json:"result,omitempty"`
	// Unix time in seconds; deadline 0 means none.
	Created  float64 `protobuf:"fixed64,11,opt,name=created,proto3" json:"created,omitempty"`
	Updated  float64 `protobuf:"fixed64,12,opt,name=updated,proto3" json:"updated,omitempty"`
	Deadline float64 `protobuf:"fixed64,13,opt,name=deadline,proto3" json:"deadline,omitempty"`
	// Empty unless the CPE is on the core or reported its SIM.
	Imsi string `protobuf:"bytes,14,opt,name=imsi,proto3" json:"imsi,omitempty"`
}

func (x *CpeTask) Reset() {
	*x = CpeTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lte_protos_cpe_acs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CpeTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpeTask) ProtoMessage() {}

func (x *CpeTask) ProtoReflect() protoreflect.Message {
	mi := &file_lte_protos_cpe_acs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpeTask.ProtoReflect.Descriptor instead.
func (*CpeTask) Descriptor() ([]byte, []int) {
	return file_lte_protos_cpe_acs_proto_rawDescGZIP(), []int{2}
}

func (x *CpeTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CpeTask) GetCpeKey() string {
	if x != nil {
		return x.CpeKey
	}
	return ""
}

func (x *CpeTask) GetType() CpeTaskType {
	if x != nil {
		return x.Type
	}
	return CpeTaskType_CPE_TASK_TYPE_UNSPECIFIED
}

func (x *CpeTask) GetStatus() CpeTaskStatus {
	if x != nil {
		return x.Status
	}
	return CpeTaskStatus_CPE_TASK_STATUS_UNSPECIFIED
}

func (x *CpeTask) GetArgs() *structpb.Struct {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *CpeTask) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *CpeTask) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *CpeTask) GetFaultCode() int32 {
	if x != nil {
		return x.FaultCode
	}
	return 0
}

func (x *CpeTask) GetFaultString() string {
	if x != nil {
		return x.FaultString
	}
	return ""
}

func (x *CpeTask) GetResult() *structpb.Struct {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CpeTask) GetCreated() float64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *CpeTask) GetUpdated() float64 {
	if x != nil {
		return x.Updated
	}
	return 0
}

func (x *CpeTask) GetDeadline() float64 {
	if x != nil {
		return x.Deadline
	}
	return 0
}

func (x *CpeTask) GetImsi() string {
	if x != nil {
		return x.Imsi
	}
	return ""
}

type GetTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lte_protos_cpe_acs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lte_protos_cpe_acs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_lte_protos_cpe_acs_proto_rawDescGZIP(), []int{3}
}

func (x *GetTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type CpeSession struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// "completed", "timed_out" or "interrupted".
	Result      string  `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Reason      string  `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Started     float64 `protobuf:"fixed64,4,opt,name=started,proto3" json:"started,omitempty"`
	Ended       float64 `protobuf:"fixed64,5,opt,name=ended,proto3" json:"ended,omitempty"`
	TasksDone   int32   `protobuf:"varint,6,opt,name=tasks_done,json=tasksDone,proto3" json:"tasks_done,omitempty"`
	TasksFailed int32   `protobuf:"varint,7,opt,name=tasks_failed,json=tasksFailed,proto3" json:"tasks_failed,omitempty"`
	Faults      int32   `protobuf:"varint,8,opt,name=faults,proto3" json:"faults,omitempty"`
}

func (x *CpeSession) Reset() {
	*x = CpeSession{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lte_protos_cpe_acs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CpeSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpeSession) ProtoMessage() {}

func (x *CpeSession) ProtoReflect() protoreflect.Message {
	mi := &file_lte_protos_cpe_acs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpeSession.ProtoReflect.Descriptor instead.
func (*CpeSession) Descriptor() ([]byte, []int) {
	return file_lte_protos_cpe_acs_proto_rawDescGZIP(), []int{4}
}

func (x *CpeSession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CpeSession) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *CpeSession) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CpeSession) GetStarted() float64 {
	if x != nil {
		return x.Started
	}
	return 0
}

func (x *CpeSession) GetEnded() float64 {
	if x != nil {
		return x.Ended
	}
	return 0
}

func (x *CpeSession) GetTasksDone() int32 {
	if x != nil {
		return x.TasksDone
	}
	return 0
}

func (x *CpeSession) GetTasksFailed() int32 {
	if x != nil {
		return x.TasksFailed
	}
	return 0
}

func (x *CpeSession) GetFaults() int32 {
	if x != nil {
		return x.Faults
	}
	return 0
}

type Cpe struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CpeKey string  `protobuf:"bytes,1,opt,name=cpe_key,json=cpeKey,proto3" json:"cpe_key,omitempty"`
	Mode   CpeMode `protobuf:"varint,2,opt,name=mode,proto3,enum=magma.lte.CpeMode" json:"mode,omitempty"`
	// Empty when unknown (a claimed CPE that did not report its SIM).
	Imsi            string `protobuf:"bytes,3,opt,name=imsi,proto3" json:"imsi,omitempty"`
	SerialNumber    string `protobuf:"bytes,4,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	Oui             string `protobuf:"bytes,5,opt,name=oui,proto3" json:"oui,omitempty"`
	ProductClass    string `protobuf:"bytes,6,opt,name=product_class,json=productClass,proto3" json:"product_class,omitempty"`
	SoftwareVersion string `protobuf:"bytes,7,opt,name=software_version,json=softwareVersion,proto3" json:"software_version,omitempty"`
	// The datamodel handler serving the CPE.
	Handler      string  `protobuf:"bytes,8,opt,name=handler,proto3" json:"handler,omitempty"`
	LastInform   float64 `protobuf:"fixed64,9,opt,name=last_inform,json=lastInform,proto3" json:"last_inform,omitempty"`
	InformsTotal int64   `protobuf:"varint,10,opt,name=informs_total,json=informsTotal,proto3" json:"informs_total,omitempty"`
	Online       bool    `protobuf:"varint,11,opt,name=online,proto3" json:"online,omitempty"`
	PendingTasks int32   `protobuf:"varint,12,opt,name=pending_tasks,json=pendingTasks,proto3" json:"pending_tasks,omitempty"`
	// Unset until a session of the CPE ends.
	LastSession *CpeSession `protobuf:"bytes,13,opt,name=last_session,json=lastSession,proto3" json:"last_session,omitempty"`
	// GetCpe only: the normalized model, its tasks in run order and, on
	// request, the raw parameter snapshot.
	Model      *structpb.Struct  `protobuf:"bytes,14,opt,name=model,proto3" json:"model,omitempty"`
	Tasks      []*CpeTask        `protobuf:"bytes,15,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Parameters map[string]string `protobuf:"bytes,16,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Cpe) Reset() {
	*x = Cpe{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lte_protos_cpe_acs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cpe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cpe) ProtoMessage() {}

func (x *Cpe) ProtoReflect() protoreflect.Message {
	mi := &file_lte_protos_cpe_acs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cpe.ProtoReflect.Descriptor instead.
func (*Cpe) Descriptor() ([]byte, []int) {
	return file_lte_protos_cpe_acs_proto_rawDescGZIP(), []int{5}
}

func (x *Cpe) GetCpeKey() string {
	if x != nil {
		return x.CpeKey
	}
	return ""
}

func (x *Cpe) GetMode() CpeMode {
	if x != nil {
		return x.Mode
	}
	return CpeMode_CPE_MODE_UNSPECIFIED
}

func (x *Cpe) GetImsi() string {
	if x != nil {
		return x.Imsi
	}
	return ""
}

func (x *Cpe) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *Cpe) GetOui() string {
	if x != nil {
		return x.Oui
	}
	return ""
}

func (x *Cpe) GetProductClass() string {
	if x != nil {
		return x.ProductClass
	}
	return ""
}

func (x *Cpe) GetSoftwareVersion() string {
	if x != nil {
		return x.SoftwareVersion
	}
	return ""
}

func (x *Cpe) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

func (x *Cpe) GetLastInform() float64 {
	if x != nil {
		return x.LastInform
	}
	return 0
}

func (x *Cpe) GetInformsTotal() int64 {
	if x != nil {
		return x.InformsTotal
	}
	return 0
}

func (x *Cpe) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *Cpe) GetPendingTasks() int32 {
	if x != nil {
		return x.PendingTasks
	}
	return 0
}

func (x *Cpe) GetLastSession() *CpeSession {
	if x != nil {
		return x.LastSession
	}
	return nil
}

func (x *Cpe) GetModel() *structpb.Struct {
	if x != nil {
		return x.Model
	}
	return nil
}

func (x *Cpe) GetTasks() []*CpeTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *Cpe) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type ListCpesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListCpesRequest) Reset() {
	*x = ListCpesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lte_protos_cpe_acs_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCpesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCpesRequest) ProtoMessage() {}

func (x *ListCpesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lte_protos_cpe_acs_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCpesRequest.ProtoReflect.Descriptor instead.
func (*ListCpesRequest) Descriptor() ([]byte, []int) {
	return file_lte_protos_cpe_acs_proto_rawDescGZIP(), []int{6}
}

type ListCpesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cpes []*Cpe `protobuf:"bytes,1,rep,name=cpes,proto3" json:"cpes,omitempty"`
}

func (x *ListCpesResponse) Reset() {
	*x = ListCpesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lte_protos_cpe_acs_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCpesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCpesResponse) ProtoMessage() {}

func (x *ListCpesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lte_protos_cpe_acs_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCpesResponse.ProtoReflect.Descriptor instead.
func (*ListCpesResponse) Descriptor() ([]byte, []int) {
	return file_lte_protos_cpe_acs_proto_rawDescGZIP(), []int{7}
}

func (x *ListCpesResponse) GetCpes() []*Cpe {
	if x != nil {
		return x.Cpes
	}
	return nil
}

type GetCpeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CpeKey            string `protobuf:"bytes,1,opt,name=cpe_key,json=cpeKey,proto3" json:"cpe_key,omitempty"`
	IncludeParameters bool   `protobuf:"varint,2,opt,name=include_parameters,json=includeParameters,proto3" json:"include_parameters,omitempty"`
}

func (x *GetCpeRequest) Reset() {
	*x = GetCpeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lte_protos_cpe_acs_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCpeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCpeRequest) ProtoMessage() {}

func (x *GetCpeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lte_protos_cpe_acs_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCpeRequest.ProtoReflect.Descriptor instead.
func (*GetCpeRequest) Descriptor() ([]byte, []int) {
	return file_lte_protos_cpe_acs_proto_rawDescGZIP(), []int{8}
}

func (x *GetCpeRequest) GetCpeKey() string {
	if x != nil {
		return x.CpeKey
	}
	return ""
}

func (x *GetCpeRequest) GetIncludeParameters() bool {
	if x != nil {
		return x.IncludeParameters
	}
	return false
}

type ConnectionRequestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CpeKey string `protobuf:"bytes,1,opt,name=cpe_key,json=cpeKey,proto3" json:"cpe_key,omitempty"`
}

func (x *ConnectionRequestRequest) Reset() {
	*x = ConnectionRequestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lte_protos_cpe_acs_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectionRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionRequestRequest) ProtoMessage() {}

func (x *ConnectionRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lte_protos_cpe_acs_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionRequestRequest.ProtoReflect.Descriptor instead.
func (*ConnectionRequestRequest) Descriptor() ([]byte, []int) {
	return file_lte_protos_cpe_acs_proto_rawDescGZIP(), []int{9}
}

func (x *ConnectionRequestRequest) GetCpeKey() string {
	if x != nil {
		return x.CpeKey
	}
	return ""
}

type ConnectionRequestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConnectionRequestResponse) Reset() {
	*x = ConnectionRequestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lte_protos_cpe_acs_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectionRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionRequestResponse) ProtoMessage() {}

func (x *ConnectionRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lte_protos_cpe_acs_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionRequestResponse.ProtoReflect.Descriptor instead.
func (*ConnectionRequestResponse) Descriptor() ([]byte, []int) {
	return file_lte_protos_cpe_acs_proto_rawDescGZIP(), []int{10}
}

var File_lte_protos_cpe_acs_proto protoreflect.FileDescriptor

var file_lte_protos_cpe_acs_proto_rawDesc = []byte{
	0x0a, 0x18, 0x6c, 0x74, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x70, 0x65,
	0x5f, 0x61, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6d, 0x61, 0x67, 0x6d,
	0x61, 0x2e, 0x6c, 0x74, 0x65, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x51, 0x0a, 0x11, 0x43, 0x70, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0xcd, 0x02, 0x0a, 0x12, 0x45, 0x6e, 0x71, 0x75, 0x65,
	0x75, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x63, 0x70, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x63, 0x70, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x2a, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6c, 0x74, 0x65,
	0x2e, 0x43, 0x70, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x61, 0x72,
	0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x47, 0x0a, 0x10, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6c, 0x74,
	0x65, 0x2e, 0x43, 0x70, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x0f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65,
	0x72, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x61,
	0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x6e,
	0x65, 0x78, 0x74, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x6e, 0x65, 0x78, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x61,
	0x78, 0x5f, 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x6d, 0x61, 0x78, 0x41, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x73, 0x12, 0x17, 0x0a,
	0x07, 0x74, 0x74, 0x6c, 0x5f, 0x73, 0x65, 0x63, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x74, 0x74, 0x6c, 0x53, 0x65, 0x63, 0x22, 0xdc, 0x03, 0x0a, 0x07, 0x43, 0x70, 0x65, 0x54, 0x61,
	0x73, 0x6b, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x63,
	0x70, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x70,
	0x65, 0x4b, 0x65, 0x79, 0x12, 0x2a, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x16, 0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6c, 0x74, 0x65, 0x2e, 0x43,
	0x70, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x30, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x18, 0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6c, 0x74, 0x65, 0x2e, 0x43, 0x70, 0x65,
	0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x2b, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x6d,
	0x61, 0x78, 0x5f, 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x6d, 0x61, 0x78, 0x41, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x73, 0x12, 0x1d,
	0x0a, 0x0a, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x21, 0x0a,
	0x0c, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x12, 0x2f, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e,
	0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x64, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6d, 0x73, 0x69, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x69, 0x6d, 0x73, 0x69, 0x22, 0x29, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64,
	0x22, 0xe5, 0x01, 0x0a, 0x0a, 0x43, 0x70, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6e, 0x64, 0x65,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x5f, 0x64, 0x6f, 0x6e, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x44, 0x6f, 0x6e, 0x65, 0x12, 0x21, 0x0a,
	0x0c, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x5f, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0b, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x90, 0x05, 0x0a, 0x03, 0x43, 0x70, 0x65,
	0x12, 0x17, 0x0a, 0x07, 0x63, 0x70, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x63, 0x70, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x26, 0x0a, 0x04, 0x6d, 0x6f, 0x64,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e,
	0x6c, 0x74, 0x65, 0x2e, 0x43, 0x70, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6d, 0x6f, 0x64,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6d, 0x73, 0x69, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x69, 0x6d, 0x73, 0x69, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x5f,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x65,
	0x72, 0x69, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x75,
	0x69, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6f, 0x75, 0x69, 0x12, 0x23, 0x0a, 0x0d,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x12, 0x29, 0x0a, 0x10, 0x73, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x5f, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x6f, 0x66,
	0x74, 0x77, 0x61, 0x72, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07,
	0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x68,
	0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x09, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x6c, 0x61, 0x73,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x6e, 0x66, 0x6f, 0x72,
	0x6d, 0x73, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c,
	0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x73, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06,
	0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6f, 0x6e,
	0x6c, 0x69, 0x6e, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f,
	0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x70, 0x65, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x38, 0x0a, 0x0c, 0x6c, 0x61, 0x73,
	0x74, 0x5f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6c, 0x74, 0x65, 0x2e, 0x43, 0x70, 0x65, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x0e, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x05, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x12, 0x28, 0x0a, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x0f, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6c, 0x74, 0x65, 0x2e, 0x43, 0x70,
	0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x3e, 0x0a, 0x0a,
	0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x10, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6c, 0x74, 0x65, 0x2e, 0x43, 0x70, 0x65,
	0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x1a, 0x3d, 0x0a, 0x0f,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x11, 0x0a, 0x0f, 0x4c,
	0x69, 0x73, 0x74, 0x43, 0x70, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x36,
	0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x70, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x63, 0x70, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6c, 0x74, 0x65, 0x2e, 0x43, 0x70, 0x65,
	0x52, 0x04, 0x63, 0x70, 0x65, 0x73, 0x22, 0x57, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x43, 0x70, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x70, 0x65, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x70, 0x65, 0x4b, 0x65, 0x79,
	0x12, 0x2d, 0x0a, 0x12, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x5f, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x69, 0x6e,
	0x63, 0x6c, 0x75, 0x64, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x22,
	0x33, 0x0a, 0x18, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63,
	0x70, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x70,
	0x65, 0x4b, 0x65, 0x79, 0x22, 0x1b, 0x0a, 0x19, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2a, 0xf9, 0x01, 0x0a, 0x0b, 0x43, 0x70, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x1d, 0x0a, 0x19, 0x43, 0x50, 0x45, 0x5f, 0x54, 0x41, 0x53, 0x4b, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x18, 0x0a, 0x14, 0x43, 0x50, 0x45, 0x5f, 0x54, 0x41, 0x53, 0x4b, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x52, 0x45, 0x42, 0x4f, 0x4f, 0x54, 0x10, 0x01, 0x12, 0x1f, 0x0a, 0x1b, 0x43, 0x50,
	0x45, 0x5f, 0x54, 0x41, 0x53, 0x4b, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x46, 0x41, 0x43, 0x54,
	0x4f, 0x52, 0x59, 0x5f, 0x52, 0x45, 0x53, 0x45, 0x54, 0x10, 0x02, 0x12, 0x19, 0x0a, 0x15, 0x43,
	0x50, 0x45, 0x5f, 0x54, 0x41, 0x53, 0x4b, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x45, 0x46,
	0x52, 0x45, 0x53, 0x48, 0x10, 0x03, 0x12, 0x26, 0x0a, 0x22, 0x43, 0x50, 0x45, 0x5f, 0x54, 0x41,
	0x53, 0x4b, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x47, 0x45, 0x54, 0x5f, 0x50, 0x41, 0x52, 0x41,
	0x4d, 0x45, 0x54, 0x45, 0x52, 0x5f, 0x56, 0x41, 0x4c, 0x55, 0x45, 0x53, 0x10, 0x04, 0x12, 0x26,
	0x0a, 0x22, 0x43, 0x50, 0x45, 0x5f, 0x54, 0x41, 0x53, 0x4b, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x53, 0x45, 0x54, 0x5f, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x45, 0x54, 0x45, 0x52, 0x5f, 0x56, 0x41,
	0x4c, 0x55, 0x45, 0x53, 0x10, 0x05, 0x12, 0x25, 0x0a, 0x21, 0x43, 0x50, 0x45, 0x5f, 0x54, 0x41,
	0x53, 0x4b, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x47, 0x45, 0x54, 0x5f, 0x50, 0x41, 0x52, 0x41,
	0x4d, 0x45, 0x54, 0x45, 0x52, 0x5f, 0x4e, 0x41, 0x4d, 0x45, 0x53, 0x10, 0x06, 0x2a, 0xc1, 0x01,
	0x0a, 0x0d, 0x43, 0x70, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x1f, 0x0a, 0x1b, 0x43, 0x50, 0x45, 0x5f, 0x54, 0x41, 0x53, 0x4b, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x1b, 0x0a, 0x17, 0x43, 0x50, 0x45, 0x5f, 0x54, 0x41, 0x53, 0x4b, 0x5f, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x5f, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x1f, 0x0a,
	0x1b, 0x43, 0x50, 0x45, 0x5f, 0x54, 0x41, 0x53, 0x4b, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x5f, 0x49, 0x4e, 0x5f, 0x50, 0x52, 0x4f, 0x47, 0x52, 0x45, 0x53, 0x53, 0x10, 0x02, 0x12, 0x18,
	0x0a, 0x14, 0x43, 0x50, 0x45, 0x5f, 0x54, 0x41, 0x53, 0x4b, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55,
	0x53, 0x5f, 0x44, 0x4f, 0x4e, 0x45, 0x10, 0x03, 0x12, 0x1a, 0x0a, 0x16, 0x43, 0x50, 0x45, 0x5f,
	0x54, 0x41, 0x53, 0x4b, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x46, 0x41, 0x49, 0x4c,
	0x45, 0x44, 0x10, 0x04, 0x12, 0x1b, 0x0a, 0x17, 0x43, 0x50, 0x45, 0x5f, 0x54, 0x41, 0x53, 0x4b,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x45, 0x58, 0x50, 0x49, 0x52, 0x45, 0x44, 0x10,
	0x05, 0x2a, 0x4c, 0x0a, 0x07, 0x43, 0x70, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x14,
	0x43, 0x50, 0x45, 0x5f, 0x4d, 0x4f, 0x44, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x43, 0x50, 0x45, 0x5f, 0x4d, 0x4f,
	0x44, 0x45, 0x5f, 0x43, 0x4f, 0x52, 0x45, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x43, 0x50, 0x45,
	0x5f, 0x4d, 0x4f, 0x44, 0x45, 0x5f, 0x43, 0x4c, 0x41, 0x49, 0x4d, 0x45, 0x44, 0x10, 0x02, 0x32,
	0xeb, 0x02, 0x0a, 0x0a, 0x43, 0x70, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12, 0x42,
	0x0a, 0x0b, 0x45, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x1d, 0x2e,
	0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6c, 0x74, 0x65, 0x2e, 0x45, 0x6e, 0x71, 0x75, 0x65, 0x75,
	0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x6d,
	0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6c, 0x74, 0x65, 0x2e, 0x43, 0x70, 0x65, 0x54, 0x61, 0x73, 0x6b,
	0x22, 0x00, 0x12, 0x3a, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x19, 0x2e,
	0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6c, 0x74, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61,
	0x2e, 0x6c, 0x74, 0x65, 0x2e, 0x43, 0x70, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x22, 0x00, 0x12, 0x45,
	0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x70, 0x65, 0x73, 0x12, 0x1a, 0x2e, 0x6d, 0x61, 0x67,
	0x6d, 0x61, 0x2e, 0x6c, 0x74, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x70, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6c,
	0x74, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x70, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x43, 0x70, 0x65, 0x12,
	0x18, 0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6c, 0x74, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x43,
	0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x6d, 0x61, 0x67, 0x6d,
	0x61, 0x2e, 0x6c, 0x74, 0x65, 0x2e, 0x43, 0x70, 0x65, 0x22, 0x00, 0x12, 0x60, 0x0a, 0x11, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x23, 0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6c, 0x74, 0x65, 0x2e, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6c, 0x74,
	0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1b, 0x5a,
	0x19, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2f, 0x6c, 0x74, 0x65, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_lte_protos_cpe_acs_proto_rawDescOnce sync.Once
	file_lte_protos_cpe_acs_proto_rawDescData = file_lte_protos_cpe_acs_proto_rawDesc
)

func file_lte_protos_cpe_acs_proto_rawDescGZIP() []byte {
	file_lte_protos_cpe_acs_proto_rawDescOnce.Do(func() {
		file_lte_protos_cpe_acs_proto_rawDescData = protoimpl.X.CompressGZIP(file_lte_protos_cpe_acs_proto_rawDescData)
	})
	return file_lte_protos_cpe_acs_proto_rawDescData
}

var file_lte_protos_cpe_acs_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_lte_protos_cpe_acs_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_lte_protos_cpe_acs_proto_goTypes = []interface{}{
	(CpeTaskType)(0),                  // 0: magma.lte.CpeTaskType
	(CpeTaskStatus)(0),                // 1: magma.lte.CpeTaskStatus
	(CpeMode)(0),                      // 2: magma.lte.CpeMode
	(*CpeParameterValue)(nil),         // 3: magma.lte.CpeParameterValue
	(*EnqueueTaskRequest)(nil),        // 4: magma.lte.EnqueueTaskRequest
	(*CpeTask)(nil),                   // 5: magma.lte.CpeTask
	(*GetTaskRequest)(nil),            // 6: magma.lte.GetTaskRequest
	(*CpeSession)(nil),                // 7: magma.lte.CpeSession
	(*Cpe)(nil),                       // 8: magma.lte.Cpe
	(*ListCpesRequest)(nil),           // 9: magma.lte.ListCpesRequest
	(*ListCpesResponse)(nil),          // 10: magma.lte.ListCpesResponse
	(*GetCpeRequest)(nil),             // 11: magma.lte.GetCpeRequest
	(*ConnectionRequestRequest)(nil),  // 12: magma.lte.ConnectionRequestRequest
	(*ConnectionRequestResponse)(nil), // 13: magma.lte.ConnectionRequestResponse
	nil,                               // 14: magma.lte.Cpe.ParametersEntry
	(*structpb.Struct)(nil),           // 15: google.protobuf.Struct
}
var file_lte_protos_cpe_acs_proto_depIdxs = []int32{
	0,  // 0: magma.lte.EnqueueTaskRequest.type:type_name -> magma.lte.CpeTaskType
	3,  // 1: magma.lte.EnqueueTaskRequest.parameter_values:type_name -> magma.lte.CpeParameterValue
	0,  // 2: magma.lte.CpeTask.type:type_name -> magma.lte.CpeTaskType
	1,  // 3: magma.lte.CpeTask.status:type_name -> magma.lte.CpeTaskStatus
	15, // 4: magma.lte.CpeTask.args:type_name -> google.protobuf.Struct
	15, // 5: magma.lte.CpeTask.result:type_name -> google.protobuf.Struct
	2,  // 6: magma.lte.Cpe.mode:type_name -> magma.lte.CpeMode
	7,  // 7: magma.lte.Cpe.last_session:type_name -> magma.lte.CpeSession
	15, // 8: magma.lte.Cpe.model:type_name -> google.protobuf.Struct
	5,  // 9: magma.lte.Cpe.tasks:type_name -> magma.lte.CpeTask
	14, // 10: magma.lte.Cpe.parameters:type_name -> magma.lte.Cpe.ParametersEntry
	8,  // 11: magma.lte.ListCpesResponse.cpes:type_name -> magma.lte.Cpe
	4,  // 12: magma.lte.CpeManager.EnqueueTask:input_type -> magma.lte.EnqueueTaskRequest
	6,  // 13: magma.lte.CpeManager.GetTask:input_type -> magma.lte.GetTaskRequest
	9,  // 14: magma.lte.CpeManager.ListCpes:input_type -> magma.lte.ListCpesRequest
	11, // 15: magma.lte.CpeManager.GetCpe:input_type -> magma.lte.GetCpeRequest
	12, // 16: magma.lte.CpeManager.ConnectionRequest:input_type -> magma.lte.ConnectionRequestRequest
	5,  // 17: magma.lte.CpeManager.EnqueueTask:output_type -> magma.lte.CpeTask
	5,  // 18: magma.lte.CpeManager.GetTask:output_type -> magma.lte.CpeTask
	10, // 19: magma.lte.CpeManager.ListCpes:output_type -> magma.lte.ListCpesResponse
	8,  // 20: magma.lte.CpeManager.GetCpe:output_type -> magma.lte.Cpe
	13, // 21: magma.lte.CpeManager.ConnectionRequest:output_type -> magma.lte.ConnectionRequestResponse
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_lte_protos_cpe_acs_proto_init() }
func file_lte_protos_cpe_acs_proto_init() {
	if File_lte_protos_cpe_acs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lte_protos_cpe_acs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CpeParameterValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lte_protos_cpe_acs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnqueueTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lte_protos_cpe_acs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CpeTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lte_protos_cpe_acs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lte_protos_cpe_acs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CpeSession); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lte_protos_cpe_acs_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cpe); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lte_protos_cpe_acs_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCpesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lte_protos_cpe_acs_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCpesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lte_protos_cpe_acs_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCpeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lte_protos_cpe_acs_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectionRequestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lte_protos_cpe_acs_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectionRequestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lte_protos_cpe_acs_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lte_protos_cpe_acs_proto_goTypes,
		DependencyIndexes: file_lte_protos_cpe_acs_proto_depIdxs,
		EnumInfos:         file_lte_protos_cpe_acs_proto_enumTypes,
		MessageInfos:      file_lte_protos_cpe_acs_proto_msgTypes,
	}.Build()
	File_lte_protos_cpe_acs_proto = out.File
	file_lte_protos_cpe_acs_proto_rawDesc = nil
	file_lte_protos_cpe_acs_proto_goTypes = nil
	file_lte_protos_cpe_acs_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CpeManagerClient is the client API for CpeManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CpeManagerClient interface {
	// Queue a task; it runs in the CPE's next CWMP session.
	// INVALID_ARGUMENT for a malformed task.
	EnqueueTask(ctx context.Context, in *EnqueueTaskRequest, opts ...grpc.CallOption) (*CpeTask, error)
	// NOT_FOUND when the task is unknown or was pruned.
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*CpeTask, error)
	// Every CPE acsd has heard from, without the model or tasks.
	ListCpes(ctx context.Context, in *ListCpesRequest, opts ...grpc.CallOption) (*ListCpesResponse, error)
	// One CPE with its normalized model and tasks. NOT_FOUND when unknown.
	GetCpe(ctx context.Context, in *GetCpeRequest, opts ...grpc.CallOption) (*Cpe, error)
	// Ask the CPE to open a session now instead of at its next periodic
	// Inform. UNIMPLEMENTED until acsd sends Connection Requests.
	ConnectionRequest(ctx context.Context, in *ConnectionRequestRequest, opts ...grpc.CallOption) (*ConnectionRequestResponse, error)
}

type cpeManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewCpeManagerClient(cc grpc.ClientConnInterface) CpeManagerClient {
	return &cpeManagerClient{cc}
}

func (c *cpeManagerClient) EnqueueTask(ctx context.Context, in *EnqueueTaskRequest, opts ...grpc.CallOption) (*CpeTask, error) {
	out := new(CpeTask)
	err := c.cc.Invoke(ctx, "/magma.lte.CpeManager/EnqueueTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cpeManagerClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*CpeTask, error) {
	out := new(CpeTask)
	err := c.cc.Invoke(ctx, "/magma.lte.CpeManager/GetTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cpeManagerClient) ListCpes(ctx context.Context, in *ListCpesRequest, opts ...grpc.CallOption) (*ListCpesResponse, error) {
	out := new(ListCpesResponse)
	err := c.cc.Invoke(ctx, "/magma.lte.CpeManager/ListCpes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cpeManagerClient) GetCpe(ctx context.Context, in *GetCpeRequest, opts ...grpc.CallOption) (*Cpe, error) {
	out := new(Cpe)
	err := c.cc.Invoke(ctx, "/magma.lte.CpeManager/GetCpe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cpeManagerClient) ConnectionRequest(ctx context.Context, in *ConnectionRequestRequest, opts ...grpc.CallOption) (*ConnectionRequestResponse, error) {
	out := new(ConnectionRequestResponse)
	err := c.cc.Invoke(ctx, "/magma.lte.CpeManager/ConnectionRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CpeManagerServer is the server API for CpeManager service.
type CpeManagerServer interface {
	// Queue a task; it runs in the CPE's next CWMP session.
	// INVALID_ARGUMENT for a malformed task.
	EnqueueTask(context.Context, *EnqueueTaskRequest) (*CpeTask, error)
	// NOT_FOUND when the task is unknown or was pruned.
	GetTask(context.Context, *GetTaskRequest) (*CpeTask, error)
	// Every CPE acsd has heard from, without the model or tasks.
	ListCpes(context.Context, *ListCpesRequest) (*ListCpesResponse, error)
	// One CPE with its normalized model and tasks. NOT_FOUND when unknown.
	GetCpe(context.Context, *GetCpeRequest) (*Cpe, error)
	// Ask the CPE to open a session now instead of at its next periodic
	// Inform. UNIMPLEMENTED until acsd sends Connection Requests.
	ConnectionRequest(context.Context, *ConnectionRequestRequest) (*ConnectionRequestResponse, error)
}

// UnimplementedCpeManagerServer can be embedded to have forward compatible implementations.
type UnimplementedCpeManagerServer struct {
}

func (*UnimplementedCpeManagerServer) EnqueueTask(context.Context, *EnqueueTaskRequest) (*CpeTask, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnqueueTask not implemented")
}
func (*UnimplementedCpeManagerServer) GetTask(context.Context, *GetTaskRequest) (*CpeTask, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTask not implemented")
}
func (*UnimplementedCpeManagerServer) ListCpes(context.Context, *ListCpesRequest) (*ListCpesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCpes not implemented")
}
func (*UnimplementedCpeManagerServer) GetCpe(context.Context, *GetCpeRequest) (*Cpe, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCpe not implemented")
}
func (*UnimplementedCpeManagerServer) ConnectionRequest(context.Context, *ConnectionRequestRequest) (*ConnectionRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConnectionRequest not implemented")
}

func RegisterCpeManagerServer(s *grpc.Server, srv CpeManagerServer) {
	s.RegisterService(&_CpeManager_serviceDesc, srv)
}

func _CpeManager_EnqueueTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnqueueTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CpeManagerServer).EnqueueTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/magma.lte.CpeManager/EnqueueTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CpeManagerServer).EnqueueTask(ctx, req.(*EnqueueTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CpeManager_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CpeManagerServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/magma.lte.CpeManager/GetTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CpeManagerServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CpeManager_ListCpes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCpesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CpeManagerServer).ListCpes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/magma.lte.CpeManager/ListCpes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CpeManagerServer).ListCpes(ctx, req.(*ListCpesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CpeManager_GetCpe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCpeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CpeManagerServer).GetCpe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/magma.lte.CpeManager/GetCpe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CpeManagerServer).GetCpe(ctx, req.(*GetCpeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CpeManager_ConnectionRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectionRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CpeManagerServer).ConnectionRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/magma.lte.CpeManager/ConnectionRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CpeManagerServer).ConnectionRequest(ctx, req.(*ConnectionRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CpeManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "magma.lte.CpeManager",
	HandlerType: (*CpeManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnqueueTask",
			Handler:    _CpeManager_EnqueueTask_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _CpeManager_GetTask_Handler,
		},
		{
			MethodName: "ListCpes",
			Handler:    _CpeManager_ListCpes_Handler,
		},
		{
			MethodName: "GetCpe",
			Handler:    _CpeManager_GetCpe_Handler,
		},
		{
			MethodName: "ConnectionRequest",
			Handler:    _CpeManager_ConnectionRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lte/protos/cpe_acs.proto",
}
