# Copyright 2026 The Magma Authors.

# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


load("@python_deps//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_binary", "py_library")
load("//bazel:test_constants.bzl", "TAG_SERVICE")

MAGMA_ROOT = "../../../../../"

ORC8R_ROOT = "{}orc8r/gateway/python".format(MAGMA_ROOT)

LTE_ROOT = "{}lte/gateway/python".format(MAGMA_ROOT)

py_binary(
    name = "acsd",
    srcs = ["main.py"],
    imports = [
        LTE_ROOT,
        ORC8R_ROOT,
    ],
    # legacy_create_init = False is required to fix issues in module import, see https://github.com/rules-proto-grpc/rules_proto_grpc/issues/145
    legacy_create_init = False,
    main = "main.py",
    tags = TAG_SERVICE,
    visibility = [
        "//:__pkg__",
        "//lte/gateway/python:__pkg__",
    ],
    deps = [":acsd_main"],
)

# main.py as a library too, so tests can import the service module.
py_library(
    name = "acsd_main",
    srcs = ["main.py"],
    visibility = ["//visibility:public"],
    deps = [
        ":acsd_identity",
        ":acsd_lib",
        ":claimed",
        ":claims",
        ":cpe_state",
        ":credentials",
        ":digest",
        ":events",
        ":metrics",
        ":rpc_servicer",
        ":server",
        ":session",
        ":store",
        "//lte/protos:mconfigs_python_proto",
        "//orc8r/gateway/python/magma/common:sentry",
        "//orc8r/gateway/python/magma/common/redis:client",
        "//orc8r/gateway/python/magma/common:service",
        "//orc8r/gateway/python/magma/configuration:service_configs",
        "//orc8r/protos:service303_python_proto",
    ],
)

py_library(
    name = "acsd_lib",
    srcs = ["config.py"],
    visibility = ["//visibility:public"],
    deps = ["//lte/protos:mconfigs_python_proto"],
)

py_library(
    name = "session",
    srcs = ["session.py"],
    visibility = ["//visibility:public"],
    deps = [
        ":acsd_lib",
        ":claimed",
        ":digest",
        ":store",
        ":tasks",
        "//lte/gateway/python/magma/acsd/datamodel",
        "//lte/gateway/python/magma/tr069:models",
        requirement("spyne"),
    ],
)

py_library(
    name = "server",
    srcs = ["server.py"],
    visibility = ["//visibility:public"],
    deps = [
        ":acsd_lib",
        ":digest",
        "//lte/gateway/python/magma/tr069:models",
        "//lte/gateway/python/magma/tr069:rpc_methods",
        "//lte/gateway/python/magma/tr069:server",
        "//lte/gateway/python/magma/tr069:spyne_mods",
        requirement("spyne"),
    ],
)

py_library(
    name = "digest",
    srcs = ["digest.py"],
    visibility = ["//visibility:public"],
)

py_library(
    name = "acsd_identity",
    srcs = [
        "bindings.py",
        "identity.py",
        "mobilityd_client.py",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//lte/protos:mobilityd_python_grpc",
        "//lte/protos:subscriberdb_python_proto",
        "//orc8r/gateway/python/magma/common:service_registry",
    ],
)

py_library(
    name = "store",
    srcs = ["store.py"],
    visibility = ["//visibility:public"],
    deps = ["//orc8r/gateway/python/magma/common/redis:containers"],
)

py_library(
    name = "tasks",
    srcs = ["tasks.py"],
    visibility = ["//visibility:public"],
    deps = [
        ":store",
        "//lte/gateway/python/magma/acsd/datamodel",
        "//lte/gateway/python/magma/tr069:models",
        requirement("spyne"),
    ],
)

py_library(
    name = "claims",
    srcs = ["claims.py"],
    visibility = ["//visibility:public"],
    deps = ["//orc8r/gateway/python/magma/common/redis:containers"],
)

py_library(
    name = "credentials",
    srcs = ["credentials.py"],
    visibility = ["//visibility:public"],
    deps = [
        ":digest",
        "//orc8r/gateway/python/magma/common/redis:containers",
    ],
)

py_library(
    name = "claimed",
    srcs = ["claimed.py"],
    visibility = ["//visibility:public"],
    deps = [
        ":claims",
        ":credentials",
        ":digest",
        ":store",
        ":tasks",
        "//lte/gateway/python/magma/acsd/datamodel",
        requirement("spyne"),
    ],
)

py_library(
    name = "cli",
    srcs = ["cli.py"],
    visibility = ["//visibility:public"],
    deps = [
        ":claims",
        ":credentials",
        "//orc8r/gateway/python/magma/common/redis:client",
    ],
)

py_library(
    name = "cpe_state",
    srcs = ["cpe_state.py"],
    visibility = ["//visibility:public"],
    deps = [
        ":acsd_lib",
        ":store",
        "//orc8r/protos:service303_python_proto",
    ],
)

py_library(
    name = "rpc_servicer",
    srcs = ["rpc_servicer.py"],
    visibility = ["//visibility:public"],
    deps = [
        ":cpe_state",
        ":store",
        ":tasks",
        "//lte/protos:cpe_acs_python_grpc",
        "//lte/protos:cpe_acs_python_proto",
        requirement("grpcio"),
    ],
)

py_library(
    name = "metrics",
    srcs = ["metrics.py"],
    visibility = ["//visibility:public"],
    deps = [
        ":cpe_state",
        ":session",
        ":store",
        requirement("prometheus_client"),
    ],
)

py_library(
    name = "events",
    srcs = ["events.py"],
    visibility = ["//visibility:public"],
    deps = [
        ":acsd_lib",
        ":cpe_state",
        ":store",
        "//orc8r/gateway/python/magma/eventd:eventd_client",
        "//orc8r/protos:eventd_python_grpc",
        requirement("prometheus_client"),
    ],
)
